### ISSUE TITLE
Adding image to policy-engine keep failing, giving exception: (500)

### ISSUE THREAD

**Issue by mc422** [anchore/anchore-engine#105]
**Is this a request for help?**:

---

BUG REPORT

```
anchore-cli --version
anchore-cli, version 0.2.4

$ docker exec aevolume_anchore-engine_1 pip show anchore-engine
Name: anchore-engine
Version: 0.2.4
Summary: Anchore Engine
Home-page: http://www.anchore.com
Author: Anchore Inc.
Author-email: dev@anchore.com
License: Apache License 2.0
Location: /usr/lib/python2.7/site-packages
Requires: Twisted, pg8000, boto3, botocore, chardet, click, clickclick, connexion, docker-py, enum34, docutils, Flask, functools32, futures, idna, inflection, itsdangerous, Jinja2, jmespath, jsonschema, MarkupSafe, pathlib, prettytable, python-dateutil, PyYAML, requests, s3transfer, six, SQLAlchemy, swagger-spec-validator, typing, urllib3, watchdog, Werkzeug, passlib, prometheus-client, prometheus-flask-exporter, psutil, python-swiftclient, python-keystoneclient, pytz, certifi
Required-by:
```

**What happened**:
I am running the Anchore Engine using docker-compose, most config is using default except that I create a separate volume using
`docker volume create -o 'o=size=4000m' -o device=tmpfs -o type=tmpfs anchore-workspace`
and using this volume for /tmp

When I am analyze one specific image, the image analysis keep failing and the log is showing this error
```
anchore-engine_1  | [service:worker] 2018-10-18 17:32:15+0000 [-] PolicyEngineClientError: Adding image to policy-engine failed - exception: (500)
anchore-engine_1  | [service:worker] 2018-10-18 17:32:15+0000 [-] [Thread-804] [anchore_engine.services.analyzer/process_analyzer_job()] [ERROR] problem analyzing image - exception: Adding image to policy-engine failed - exception: (500)
```

I check system status and everything is up

```
$ anchore-cli system status
Service simplequeue (dockerhostid-anchore-engine, http://anchore-engine:8083): up
Service apiext (dockerhostid-anchore-engine, http://anchore-engine:8228): up
Service kubernetes_webhook (dockerhostid-anchore-engine, http://anchore-engine:8338): up
Service analyzer (dockerhostid-anchore-engine, http://anchore-engine:8084): up
Service policy_engine (dockerhostid-anchore-engine, http://anchore-engine:8087): up
Service catalog (dockerhostid-anchore-engine, http://anchore-engine:8082): up

Engine DB Version: 0.0.7
Engine Code Version: 0.2.4
```

When I exec into the container and pull out the `anchore-policy-engine.log`, I see this error

```
2018-10-18 17:32:15+0000 [-] Traceback (most recent call last):
2018-10-18 17:32:15+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/policy_engine/engine/tasks.py", line 497, in _load_image_analysis
2018-10-18 17:32:15+0000 [-]     result = loader.load()
2018-10-18 17:32:15+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/policy_engine/engine/loaders.py", line 119, in load
2018-10-18 17:32:15+0000 [-]     image.fs = self.load_fsdump(analysis_report)
2018-10-18 17:32:15+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/policy_engine/engine/loaders.py", line 447, in load_fsdump
2018-10-18 17:32:15+0000 [-]     path_map = {path: json.loads(value) for path, value in all_infos.items()}
2018-10-18 17:32:15+0000 [-] AttributeError: 'list' object has no attribute 'items'
2018-10-18 17:32:15+0000 [_GenericHTTPChannelProtocol,2,172.18.0.3] [PoolThread-twisted.internet.reactor-0] [anchore_engine.services.policy_engine.engine.logs/exception()] [ERROR] Exception in image loader
2018-10-18 17:32:15+0000 [-] Traceback (most recent call last):
2018-10-18 17:32:15+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/policy_engine/engine/tasks.py", line 452, in execute
2018-10-18 17:32:15+0000 [-]     image_obj = self._load_image_analysis()
2018-10-18 17:32:15+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/policy_engine/engine/tasks.py", line 497, in _load_image_analysis
2018-10-18 17:32:15+0000 [-]     result = loader.load()
2018-10-18 17:32:15+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/policy_engine/engine/loaders.py", line 119, in load
2018-10-18 17:32:15+0000 [-]     image.fs = self.load_fsdump(analysis_report)
2018-10-18 17:32:15+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/policy_engine/engine/loaders.py", line 447, in load_fsdump
2018-10-18 17:32:15+0000 [-]     path_map = {path: json.loads(value) for path, value in all_infos.items()}
2018-10-18 17:32:15+0000 [-] AttributeError: 'list' object has no attribute 'items'
2018-10-18 17:32:15+0000 [_GenericHTTPChannelProtocol,2,172.18.0.3] [PoolThread-twisted.internet.reactor-0] [anchore_engine.services.policy_engine.engine.logs/exception()] [ERROR] Error loading and scanning image: aaf84a49facd8826ada9d6091fd2d0793cdacac552f74f29abd77ed6b2c32797
```

Can someone explain what this error means and how to fix it. Thank you.

**Comment by nurmi** [comment]
Hi @mc422,

This looks like a bug, where the loader in the policy engine is defaulting to an empty list when there are no files in the analysis data instead of an empty dictionary (when there are files in the analysis data, they are contained in a dictionary).  

We'll fix the bug for an upcoming release, but the question still remains on why there is an image being analyzed that either has no files at all - is this correct that the image in question being scanned actually has no files in it?  I wanted to ask in case there is potentially some other issue at play here.
