### ISSUE TITLE
Worker says "failed to PUT to catalog" but catalog log says the PUT went ok

### ISSUE THREAD

**Issue by paulcdejean** [anchore/anchore-engine#108]
```
[root@ip-10-2-60-103 anchore]# grep '37db6de5d7c2d254740d65af75c3ccec304a6b061ae146334f475588a0e0232c' anchore-catalog.log
2018-10-23 17:04:27+0000 [-] "127.0.0.1" - - [23/Oct/2018:17:04:26 +0000] "GET /v1/image/sha256:37db6de5d7c2d254740d65af75c3ccec304a6b061ae146334f475588a0e0232c HTTP/1.1" 200 1233 "-" "python-requests/2.18.0"
2018-10-23 17:04:27+0000 [-] "127.0.0.1" - - [23/Oct/2018:17:04:26 +0000] "PUT /v1/image/sha256:37db6de5d7c2d254740d65af75c3ccec304a6b061ae146334f475588a0e0232c HTTP/1.1" 200 1230 "-" "python-requests/2.18.0"
[root@ip-10-2-60-103 anchore]# tail anchore-worker.log
2018-10-23 17:06:19+0000 [-] Exception in thread Thread-89551:
2018-10-23 17:06:19+0000 [-] Traceback (most recent call last):
2018-10-23 17:06:19+0000 [-]   File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
2018-10-23 17:06:19+0000 [-]     self.run()
2018-10-23 17:06:19+0000 [-]   File "/usr/lib64/python2.7/threading.py", line 765, in run
2018-10-23 17:06:19+0000 [-]     self.__target(*self.__args, **self.__kwargs)
2018-10-23 17:06:19+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/analyzer/__init__.py", line 466, in process_analyzer_job
2018-10-23 17:06:19+0000 [-]     raise err
2018-10-23 17:06:19+0000 [-] Exception: failed put url=http://127.0.0.1:8082/v1/image/sha256:37db6de5d7c2d254740d65af75c3ccec304a6b061ae146334f475588a0e0232c
2018-10-23 17:06:19+0000 [-]
[root@ip-10-2-60-103 anchore]#
```

**Comment by paulcdejean** [comment]
Wait the timestamps don't line up sorry.
