### ISSUE TITLE
analysis_failed for kaniko built images

### ISSUE THREAD

**Issue by gmatuz** [anchore/anchore-engine#131]
**Is this a request for help?**:

No

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:
0.3.0
 
**What happened**:
analysis_failed for images built (and pushed) with kaniko 
(might also be specific to the registry being used, in this case Artifactory)

**What did you expect to happen**:
Images built by kaniko are fully functional, also can be pulled directly with docker or inspected with skopeo

**Any relevant log output from /var/log/anchore**:
2019-01-15 09:32:40+0000 [-] [Thread-207026] [anchore_engine.services.analyzer/perform_analyze_nodocker()] [INFO] performing analysis on image: ['admin', 'redactedimage@sha256:410294e8de77fed2526122c8cd75c3ce11fd8f8deb370995b0bf69879adf988c', 'redactedimage:specifictag']
2019-01-15 09:32:41+0000 [-] [Thread-207026] [anchore_engine.clients.skopeo_wrapper/download_image()] [ERROR] command failed with exception - Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  copy --src-tls-verify=true --src-creds "${SKOPUSER}":"${SKOPPASS}"  docker://redactedimage@sha256:410294e8de77fed2526122c8cd75c3ce11fd8f8deb370995b0bf69879adf988c oci:/analysis_scratch/22e89bc2-b524-452a-a42d-3f26dbcab967/raw:image, rc=1, stdout=None, stderr=b'time="2019-01-15T09:32:41Z" level=fatal msg="Error determining manifest MIME type for docker://redactedimage@sha256:410294e8de77fed2526122c8cd75c3ce11fd8f8deb370995b0bf69879adf988c: Error reading manifest sha256:410294e8de77fed2526122c8cd75c3ce11fd8f8deb370995b0bf69879adf988c in redactedimage: manifest unknown: The named manifest is not known to the registry." \n'
2019-01-15 09:32:41+0000 [-] Traceback (most recent call last):
2019-01-15 09:32:41+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/anchore_engine/clients/localanchore_standalone.py", line 770, in analyze_image
2019-01-15 09:32:41+0000 [-]     rc = pull_image(staging_dirs, pullstring, registry_creds=registry_creds, manifest=manifest, dest_type=dest_type)
2019-01-15 09:32:41+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/anchore_engine/clients/localanchore_standalone.py", line 383, in pull_image
2019-01-15 09:32:41+0000 [-]     raise err
2019-01-15 09:32:41+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/anchore_engine/clients/localanchore_standalone.py", line 381, in pull_image
2019-01-15 09:32:41+0000 [-]     rc = anchore_engine.clients.skopeo_wrapper.download_image(pullstring, copydir, user=user, pw=pw, verify=registry_verify, manifest=manifest, use_cache_dir=cachedir, dest_type=dest_type)
2019-01-15 09:32:41+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/anchore_engine/clients/skopeo_wrapper.py", line 102, in download_image
2019-01-15 09:32:41+0000 [-]     raise err
2019-01-15 09:32:41+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/anchore_engine/clients/skopeo_wrapper.py", line 100, in download_image
2019-01-15 09:32:41+0000 [-]     raise err
2019-01-15 09:32:41+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/anchore_engine/clients/skopeo_wrapper.py", line 94, in download_image
2019-01-15 09:32:41+0000 [-]     raise SkopeoError(cmd=cmd, rc=rc, out=sout, err=serr)
2019-01-15 09:32:41+0000 [-] anchore_engine.clients.skopeo_wrapper.SkopeoError: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  copy --src-tls-verify=true --src-creds "${SKOPUSER}":"${SKOPPASS}"  docker:/redactedimage@sha256:410294e8de77fed2526122c8cd75c3ce11fd8f8deb370995b0bf69879adf988c oci:/analysis_scratch/22e89bc2-b524-452a-a42d-3f26dbcab967/raw:image, rc=1, stdout=None, stderr=b'time="2019-01-15T09:32:41Z" level=fatal msg="Error determining manifest MIME type for docker://redactedimage@sha256:410294e8de77fed2526122c8cd75c3ce11fd8f8deb370995b0bf69879adf988c: Error reading manifest sha256:410294e8de77fed2526122c8cd75c3ce11fd8f8deb370995b0bf69879adf988c in redactedimage: manifest unknown: The named manifest is not known to the registry." \n'
2019-01-15 09:32:41+0000 [-] 
2019-01-15 09:32:41+0000 [-] During handling of the above exception, another exception occurred:
2019-01-15 09:32:41+0000 [-] 
2019-01-15 09:32:41+0000 [-] Traceback (most recent call last):
2019-01-15 09:32:41+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/anchore_engine/services/analyzer/__init__.py", line 136, in process_analyzer_job
2019-01-15 09:32:41+0000 [-]     image_data = perform_analyze(userId, manifest, image_record, registry_creds, layer_cache_enable=layer_cache_enable)
2019-01-15 09:32:41+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/anchore_engine/services/analyzer/__init__.py", line 41, in perform_analyze
2019-01-15 09:32:41+0000 [-]     return perform_analyze_nodocker(userId, manifest, image_record, registry_creds, layer_cache_enable=layer_cache_enable)
2019-01-15 09:32:41+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/anchore_engine/services/analyzer/__init__.py", line 76, in perform_analyze_nodocker
2019-01-15 09:32:41+0000 [-]     analyzed_image_report = localanchore_standalone.analyze_image(userId, registry_manifest, image_record, tmpdir, localconfig, registry_creds=registry_creds, use_cache_dir=use_cache_dir)
2019-01-15 09:32:41+0000 [-]   File "/usr/local/lib/python3.6/dist-packages/anchore_engine/clients/localanchore_standalone.py", line 772, in analyze_image
2019-01-15 09:32:41+0000 [-]     raise ImagePullError(cause=err, pull_string=pullstring, tag=fulltag)
2019-01-15 09:32:41+0000 [-] anchore_engine.clients.localanchore_standalone.ImagePullError: Failed to pull image (redactedimage@sha256:410294e8de77fed2526122c8cd75c3ce11fd8f8deb370995b0bf69879adf988c) - exception: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  copy --src-tls-verify=true --src-creds "${SKOPUSER}":"${SKOPPASS}"  docker://redactedimage@sha256:410294e8de77fed2526122c8cd75c3ce11fd8f8deb370995b0bf69879adf988c oci:/analysis_scratch/22e89bc2-b524-452a-a42d-3f26dbcab967/raw:image, rc=1, stdout=None, stderr=b'time="2019-01-15T09:32:41Z" level=fatal msg="Error determining manifest MIME type for docker://redactedimage@sha256:410294e8de77fed2526122c8cd75c3ce11fd8f8deb370995b0bf69879adf988c: Error reading manifest sha256:410294e8de77fed2526122c8cd75c3ce11fd8f8deb370995b0bf69879adf988c in redactedimage: manifest unknown: The named manifest is not known to the registry." \n'
2019-01-15 09:32:41+0000 [-] [Thread-207026] [anchore_engine.services.analyzer/process_analyzer_job()] [ERROR] problem analyzing image - exception: Failed to pull image (redactedimage@sha256:410294e8de77fed2526122c8cd75c3ce11fd8f8deb370995b0bf69879adf988c) - exception: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  copy --src-tls-verify=true --src-creds "${SKOPUSER}":"${SKOPPASS}"  docker://redactedimage@sha256:410294e8de77fed2526122c8cd75c3ce11fd8f8deb370995b0bf69879adf988c oci:/analysis_scratch/22e89bc2-b524-452a-a42d-3f26dbcab967/raw:image, rc=1, stdout=None, stderr=b'time="2019-01-15T09:32:41Z" level=fatal msg="Error determining manifest MIME type for docker://redactedimage@sha256:410294e8de77fed2526122c8cd75c3ce11fd8f8deb370995b0bf69879adf988c: Error reading manifest sha256:410294e8de77fed2526122c8cd75c3ce11fd8f8deb370995b0bf69879adf988c in redactedimage: manifest unknown: The named manifest is not known to the registry." \n'

**What docker images are you using**:
Anything built with kaniko

**How to reproduce the issue**:

**Anything else we need to know**:
was able to fix the error, which is most likely caused by some encoding/content-type difference, by switching to skopeo to calculate the digest (which it does correctly) instead of own implementation here:
https://github.com/anchore/anchore-engine/blob/580f6d4164d2cbdc9ee8594c3e1f71a1055483cd/anchore_engine/utils.py#L205-L215

**Comment by nurmi** [comment]
hi @gmatuz - thanks for the detailed report!  I agree with  your findings and that it is likely that digest calculation is the culprit here.  Would it be at all possible to make available a public image that exhibits this problem so that we might investigate the manifest format (or post the raw manifest from skopeo)?  e.g.

```
skopeo inspect --raw docker://docker.io/alpine@sha256:3d2e482b82608d153a374df3357c0291589a61cc194ec4a9ca2381073a17f58e
```

**Comment by donchev7** [comment]
Hi @nurmi ,

With python:
```
>>> with open('manifest3.json', 'r') as r:
...     rawmanifest = r.read()
...     d = json.loads(rawmanifest, object_pairs_hook=OrderedDict)
...     if d['schemaVersion'] != 1:
...         d.pop('signatures', None)
...         # this is using regular json
...         dmanifest = re.sub(" +\n", "\n", json.dumps(d, indent=3))
...         # this if using simplejson
...         #dmanifest = json.dumps(d, indent=3)
...         ret = "sha256:" + str(hashlib.sha256(dmanifest.encode('utf-8')).hexdigest())
...         print(ret)
... 
sha256:660d225d6e463bbb26cee2c440e0d559c56c45fd86e5407ff715b3de4c98ad6f
```
but with skopeo
```
skopeo manifest-digest manifest3.json 
sha256:a43708a75dbaa522407955888ccd13024e35eec65fa7e163c9a09dc76485b0ab
```

the **manifest3.json** you can find here https://pastebin.com/kJjUQGNU

**Comment by donchev7** [comment]
I pulled the manifest file from our registry with:
```
skopeo inspect --creds privateRepo:Artifactory --raw docker://some.private.jfrog.io/somecontainer:latest > manifest3.json
```
anchore also uses skopeo inspect to pull the manifest file

**Comment by nurmi** [comment]
update: the core issue here is that the anchore routine is assuming indented formatting of the image manifest from registry, but this kaniko generated manifest is not indented, thus some of the formatting that is being performed is changing the content and resulting in a different (incorrect) digest.  

We're working on a fix that will resolve this issue, but still keep the digest calculation as native python code in anchore - previously we had performed a shell-out but this results in measurable cycles when an anchore engine is iterating over many thousands of images, so it is preferable to keep this routine implemented in python if possible.  

Will update the ticket when a fix is merged to master!
