### ISSUE TITLE
Link-related errors while analyzing image

### ISSUE THREAD

**Issue by mattpag** [anchore/anchore-engine#213]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): Bug report

**Version of Anchore Engine and Anchore CLI if applicable**: 0.4.0

 
**What happened**: Can't analyze image `docker.io/cockpit/kubernetes:latest`

**Any relevant log output from /var/log/anchore**:
```
[service:worker] 2019-06-10 09:19:38+0000 [-] [Thread-137] [anchore_engine.services.analyzer/process_analyzer_job()] [INFO] image dequeued for analysis: admin : sha256:f38c7b0d2b85989f058bf78c1759bec5b5d633f26651ea74753eac98f9e70c9b
[service:worker] 2019-06-10 09:19:38+0000 [-] [Thread-137] [anchore_engine.services.analyzer/perform_analyze_nodocker()] [INFO] performing analysis on image: ['admin', 'docker.io/cockpit/kubernetes@sha256:f38c7b0d2b85989f058bf78c1759bec5b5d633f26651ea74753eac98f9e70c9b', 'docker.io/cockpit/kubernetes:latest']
[service:worker] 2019-06-10 09:20:05+0000 [-] [Thread-137] [anchore_engine.clients.localanchore_standalone/run_anchore_analyzers()] [ERROR] command failed with exception - command failed: cmd=/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/analyzers/modules/01_analyzer_meta.py /home/anchore/config 4ec8c5b8a4869cab76b887d508a5389d2070bfd311871961f22e638907d99d31 /home/anchore/analysis_scratch/c914a7ac-02df-4c25-a20e-c45aae80b07c /home/anchore/analysis_scratch/c914a7ac-02df-4c25-a20e-c45aae80b07c/output /home/anchore/analysis_scratch/c914a7ac-02df-4c25-a20e-c45aae80b07c exitcode=1 stdout= stderr=Traceback (most recent call last):
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/analyzers/modules/01_analyzer_meta.py", line 44, in <module>
[service:worker] 	    raise err
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/analyzers/modules/01_analyzer_meta.py", line 24, in <module>
[service:worker] 	    meta = anchore_engine.analyzers.utils.get_distro_from_squashtar(os.path.join(unpackdir, "squashed.tar"))
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/analyzers/utils.py", line 154, in get_distro_from_squashtar
[service:worker] 	    with tfl.extractfile(tfl.getmember(metamap['os-release'])) as FH:
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/tarfile.py", line 2089, in extractfile
[service:worker] 	    return self.extractfile(self._find_link_target(tarinfo))
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/tarfile.py", line 2385, in _find_link_target
[service:worker] 	    raise KeyError("linkname %r not found" % linkname)
[service:worker] 	KeyError: "linkname 'etc//container/os-release' not found"
[service:worker] 2019-06-10 09:20:06+0000 [-] [Thread-137] [anchore_engine.clients.localanchore_standalone/run_anchore_analyzers()] [ERROR] command failed with exception - command failed: cmd=/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/analyzers/modules/10_package_list.py /home/anchore/config 4ec8c5b8a4869cab76b887d508a5389d2070bfd311871961f22e638907d99d31 /home/anchore/analysis_scratch/c914a7ac-02df-4c25-a20e-c45aae80b07c /home/anchore/analysis_scratch/c914a7ac-02df-4c25-a20e-c45aae80b07c/output /home/anchore/analysis_scratch/c914a7ac-02df-4c25-a20e-c45aae80b07c exitcode=1 stdout= stderr=Traceback (most recent call last):
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/analyzers/modules/10_package_list.py", line 21, in <module>
[service:worker] 	    meta = anchore_engine.analyzers.utils.get_distro_from_squashtar(os.path.join(unpackdir, "squashed.tar"), unpackdir=unpackdir)
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/analyzers/utils.py", line 154, in get_distro_from_squashtar
[service:worker] 	    with tfl.extractfile(tfl.getmember(metamap['os-release'])) as FH:
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/tarfile.py", line 2089, in extractfile
[service:worker] 	    return self.extractfile(self._find_link_target(tarinfo))
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/tarfile.py", line 2385, in _find_link_target
[service:worker] 	    raise KeyError("linkname %r not found" % linkname)
[service:worker] 	KeyError: "linkname 'etc//container/os-release' not found"
[service:worker] 2019-06-10 09:20:15+0000 [-] [Thread-137] [anchore_engine.clients.localanchore_standalone/run_anchore_analyzers()] [ERROR] command failed with exception - command failed: cmd=/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/analyzers/modules/20_file_list.py /home/anchore/config 4ec8c5b8a4869cab76b887d508a5389d2070bfd311871961f22e638907d99d31 /home/anchore/analysis_scratch/c914a7ac-02df-4c25-a20e-c45aae80b07c /home/anchore/analysis_scratch/c914a7ac-02df-4c25-a20e-c45aae80b07c/output /home/anchore/analysis_scratch/c914a7ac-02df-4c25-a20e-c45aae80b07c exitcode=1 stdout= stderr=Traceback (most recent call last):
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/analyzers/modules/20_file_list.py", line 25, in <module>
[service:worker] 	    meta = anchore_engine.analyzers.utils.get_distro_from_squashtar(os.path.join(unpackdir, "squashed.tar"), unpackdir=unpackdir)
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/analyzers/utils.py", line 154, in get_distro_from_squashtar
[service:worker] 	    with tfl.extractfile(tfl.getmember(metamap['os-release'])) as FH:
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/tarfile.py", line 2089, in extractfile
[service:worker] 	    return self.extractfile(self._find_link_target(tarinfo))
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/tarfile.py", line 2385, in _find_link_target
[service:worker] 	    raise KeyError("linkname %r not found" % linkname)
[service:worker] 	KeyError: "linkname 'etc//container/os-release' not found"
[service:worker] 2019-06-10 09:20:16+0000 [-] [Thread-137] [anchore_engine.clients.localanchore_standalone/run_anchore_analyzers()] [ERROR] command failed with exception - command failed: cmd=/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/analyzers/modules/30_file_checksums.py /home/anchore/config 4ec8c5b8a4869cab76b887d508a5389d2070bfd311871961f22e638907d99d31 /home/anchore/analysis_scratch/c914a7ac-02df-4c25-a20e-c45aae80b07c /home/anchore/analysis_scratch/c914a7ac-02df-4c25-a20e-c45aae80b07c/output /home/anchore/analysis_scratch/c914a7ac-02df-4c25-a20e-c45aae80b07c exitcode=1 stdout= stderr=Traceback (most recent call last):
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/analyzers/modules/30_file_checksums.py", line 31, in <module>
[service:worker] 	    meta = anchore_engine.analyzers.utils.get_distro_from_squashtar(os.path.join(unpackdir, "squashed.tar"), unpackdir=unpackdir)
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/analyzers/utils.py", line 154, in get_distro_from_squashtar
[service:worker] 	    with tfl.extractfile(tfl.getmember(metamap['os-release'])) as FH:
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/tarfile.py", line 2089, in extractfile
[service:worker] 	    return self.extractfile(self._find_link_target(tarinfo))
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/tarfile.py", line 2385, in _find_link_target
[service:worker] 	    raise KeyError("linkname %r not found" % linkname)
[service:worker] 	KeyError: "linkname 'etc//container/os-release' not found"
[service:worker] 2019-06-10 09:20:16+0000 [-] [Thread-137] [anchore_engine.clients.localanchore_standalone/run_anchore_analyzers()] [ERROR] command failed with exception - command failed: cmd=/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/analyzers/modules/31_file_package_verify.py /home/anchore/config 4ec8c5b8a4869cab76b887d508a5389d2070bfd311871961f22e638907d99d31 /home/anchore/analysis_scratch/c914a7ac-02df-4c25-a20e-c45aae80b07c /home/anchore/analysis_scratch/c914a7ac-02df-4c25-a20e-c45aae80b07c/output /home/anchore/analysis_scratch/c914a7ac-02df-4c25-a20e-c45aae80b07c exitcode=1 stdout= stderr=Traceback (most recent call last):
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/analyzers/modules/31_file_package_verify.py", line 27, in <module>
[service:worker] 	    meta = anchore_engine.analyzers.utils.get_distro_from_squashtar(squashtar, unpackdir=unpackdir)
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/analyzers/utils.py", line 154, in get_distro_from_squashtar
[service:worker] 	    with tfl.extractfile(tfl.getmember(metamap['os-release'])) as FH:
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/tarfile.py", line 2089, in extractfile
[service:worker] 	    return self.extractfile(self._find_link_target(tarinfo))
[service:worker] 	  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/tarfile.py", line 2385, in _find_link_target
[service:worker] 	    raise KeyError("linkname %r not found" % linkname)
[service:worker] 	KeyError: "linkname 'etc//container/os-release' not found"
[service:worker] 2019-06-10 09:20:19+0000 [-] [Thread-137] [anchore_engine.services.analyzer/perform_analyze_nodocker()] [INFO] performing analysis on image complete: docker.io/cockpit/kubernetes@sha256:f38c7b0d2b85989f058bf78c1759bec5b5d633f26651ea74753eac98f9e70c9b
[service:worker] 2019-06-10 09:20:19+0000 [-] [Thread-137] [anchore_engine.common.helpers/extract_analyzer_content()] [WARN] exception: could not extract/parse content info - exception: 'file_checksums'
[service:worker] 2019-06-10 09:20:19+0000 [-] Traceback (most recent call last):
[service:worker] 2019-06-10 09:20:19+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/analyzer/__init__.py", line 172, in process_analyzer_job
[service:worker] 2019-06-10 09:20:19+0000 [-]     raise err
[service:worker] 2019-06-10 09:20:19+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/analyzer/__init__.py", line 169, in process_analyzer_job
[service:worker] 2019-06-10 09:20:19+0000 [-]     anchore_engine.common.helpers.update_image_record_with_analysis_data(image_record, image_data)
[service:worker] 2019-06-10 09:20:19+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/common/helpers.py", line 151, in update_image_record_with_analysis_data
[service:worker] 2019-06-10 09:20:19+0000 [-]     if formatted_image_summary_data:
[service:worker] 2019-06-10 09:20:19+0000 [-] UnboundLocalError: local variable 'formatted_image_summary_data' referenced before assignment
[service:worker] 2019-06-10 09:20:19+0000 [-] [Thread-137] [anchore_engine.services.analyzer/process_analyzer_job()] [WARN] could not store image content metadata to archive - exception: local variable 'formatted_image_summary_data' referenced before assignment
[service:worker] 2019-06-10 09:20:19+0000 [-] [Thread-137] [anchore_engine.services.analyzer/process_analyzer_job()] [INFO] Loading image into policy engine: admin 4ec8c5b8a4869cab76b887d508a5389d2070bfd311871961f22e638907d99d31
[service:worker] 2019-06-10 09:20:19+0000 [-] [Thread-137] [anchore_engine.clients.services.internal/dispatch()] [ERROR] Failed client call to service policy_engine for url: http://localhost:8087/v1/images. Response: {'httpcode': 500, 'anchore_error_raw': 'b\'{\\n  "detail": {\\n    "error_codes": []\\n  },\\n  "httpcode": 500,\\n  "message": "\\\'analyzer_meta\\\'"\\n}\\n\'', 'anchore_error_json': {'detail': {'error_codes': []}, 'httpcode': 500, 'message': "'analyzer_meta'"}}
[service:worker] 2019-06-10 09:20:19+0000 [-] Traceback (most recent call last):
[service:worker] 2019-06-10 09:20:19+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/analyzer/__init__.py", line 198, in process_analyzer_job
[service:worker] 2019-06-10 09:20:19+0000 [-]     resp = pe_client.ingress_image(userId, imageId, image_analysis_fetch_url)
[service:worker] 2019-06-10 09:20:19+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/services/policy_engine.py", line 14, in ingress_image
[service:worker] 2019-06-10 09:20:19+0000 [-]     return self.call_api(anchy_post, 'images', body=json.dumps({'user_id': user_id, 'image_id': image_id, 'fetch_url': analysis_fetch_url}))
[service:worker] 2019-06-10 09:20:19+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/services/internal.py", line 120, in call_api
[service:worker] 2019-06-10 09:20:19+0000 [-]     return self.dispatch(base_url, method, path, path_params, query_params, extra_headers, body, connect_timeout, read_timeout)
[service:worker] 2019-06-10 09:20:19+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/services/internal.py", line 167, in dispatch
[service:worker] 2019-06-10 09:20:19+0000 [-]     raise e
[service:worker] 2019-06-10 09:20:19+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/services/internal.py", line 164, in dispatch
[service:worker] 2019-06-10 09:20:19+0000 [-]     return method(url=final_url, headers=request_headers, data=body, auth=(self.user, self.password), params=filtered_qry_params, verify=self.verify_ssl)
[service:worker] 2019-06-10 09:20:19+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/services/http.py", line 269, in anchy_post
[service:worker] 2019-06-10 09:20:19+0000 [-]     raise e
[service:worker] 2019-06-10 09:20:19+0000 [-] Exception: failed post url=http://localhost:8087/v1/images
[service:worker] 2019-06-10 09:20:19+0000 [-] 
[service:worker] 2019-06-10 09:20:19+0000 [-] During handling of the above exception, another exception occurred:
[service:worker] 2019-06-10 09:20:19+0000 [-] 
[service:worker] 2019-06-10 09:20:19+0000 [-] Traceback (most recent call last):
[service:worker] 2019-06-10 09:20:19+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/analyzer/__init__.py", line 204, in process_analyzer_job
[service:worker] 2019-06-10 09:20:19+0000 [-]     raise newerr
[service:worker] 2019-06-10 09:20:19+0000 [-] anchore_engine.services.analyzer.PolicyEngineClientError: Adding image to policy-engine failed - exception: failed post url=http://localhost:8087/v1/images
[service:worker] 2019-06-10 09:20:19+0000 [-] [Thread-137] [anchore_engine.services.analyzer/process_analyzer_job()] [ERROR] problem analyzing image - exception: Adding image to policy-engine failed - exception: failed post url=http://localhost:8087/v1/images
```

**What docker images are you using**: `docker.io/anchore/anchore-engine:v0.4.0`

**How to reproduce the issue**: Request analysis of `docker.io/cockpit/kubernetes:latest`

**Comment by nurmi** [comment]
Thanks @mattpag for the report - the issue here turned out to be related to the fact that, for that image, the /etc/os-release file was a softlink to /container/os-release, but that destination file did not exist and was triggering this exception/bug in the anchore analyzer.

```
# ls -l /etc/os-release 
lrwxrwxrwx 1 root root 21 Oct 12  2018 /etc/os-release -> /container/os-release
# ls -l /container/os-release
ls: cannot access '/container/os-release': No such file or directory
#
```

We've made an update to the analyzer to handle this condition that will be available in the next OSS release.
