### ISSUE TITLE
Analyzer Sending Wrong File Size, causes Policy Engine to Fail

### ISSUE THREAD

**Issue by adawalli** [anchore/anchore-engine#239]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:
anchore-cli, version 0.4.1

 ```
Name: anchore-engine
Version: 0.4.1
Summary: Anchore Engine
Home-page: http://www.anchore.com
Author: Anchore Inc.
Author-email: dev@anchore.com
License: Apache License 2.0
Location: /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages
Requires: yosai, MarkupSafe, prometheus-client, PyYAML, botocore, urllib3, s3transfer, zope.interface, Flask, semantic-version, itsdangerous, Werkzeug, connexion, click, jsonschema, python-dateutil, docutils, psycopg2-binary, idna, chardet, toastedmarshmallow, prometheus-flask-exporter, pathlib, prettytable, pg8000, inflection, Jinja2, typing, watchdog, six, zope.component, python-keystoneclient, clickclick, python-swiftclient, certifi, swagger-spec-validator, retrying, passlib, Twisted, jmespath, pytz, SQLAlchemy, boto3, psutil, requests
```
**What happened**:
Anchore Engine attempts to load image into policy engine, which fails. On the the policy engine side, the logs indicate that an SQL INSERT fails due to an "integer out of range".  This appears to be because of a bug in interpreting the debian package size. Logs will be shown below.

**What did you expect to happen**: I expected the policy engine to not fail.

**Any relevant log output from /var/log/anchore**:
**Relevant Logs From Policy Container**
```
2019-07-24 15:45:46+0000 [-] (Background on this error at: http://sqlalche.me/e/9h9h)                                                                                                                                               [20/46754]
2019-07-24 15:45:46+0000 [_GenericHTTPChannelProtocol,367,172.18.0.7] [PoolThread-twisted.internet.reactor-0] [anchore_engine.services.policy_engine.engine.logs/exception()] [ERROR] Error loading and scanning image: a34743cbdafc54ab377467
50d489ba847fdc479d8861ef976281b2b00c22ee5b
2019-07-24 15:45:46+0000 [-] Traceback (most recent call last):
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
2019-07-24 15:45:46+0000 [-]     cursor, statement, parameters, context
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
2019-07-24 15:45:46+0000 [-]     cursor.execute(statement, parameters)
2019-07-24 15:45:46+0000 [-] psycopg2.DataError: integer out of range
2019-07-24 15:45:46+0000 [-]
2019-07-24 15:45:46+0000 [-]
2019-07-24 15:45:46+0000 [-] The above exception was the direct cause of the following exception:
2019-07-24 15:45:46+0000 [-]
2019-07-24 15:45:46+0000 [-] Traceback (most recent call last):
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/policy_engine/api/controllers/synchronous_operations.py", line 720, in ingress_image
2019-07-24 15:45:46+0000 [-]     result = t.execute()
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/tasks.py", line 465, in execute
2019-07-24 15:45:46+0000 [-]     vulns = vulnerabilities_for_image(image_obj)
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/vulnerabilities.py", line 154, in vulnerabilities_for_image
2019-07-24 15:45:46+0000 [-]     for package in image_obj.packages:
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/orm/dynamic.py", line 292, in __iter__
2019-07-24 15:45:46+0000 [-]     sess = self.session
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/orm/dynamic.py", line 283, in session
2019-07-24 15:45:46+0000 [-]     sess.flush()
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2451, in flush
2019-07-24 15:45:46+0000 [-]     self._flush(objects)
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2589, in _flush
2019-07-24 15:45:46+0000 [-]     transaction.rollback(_capture_exception=True)
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
2019-07-24 15:45:46+0000 [-]     compat.reraise(exc_type, exc_value, exc_tb)
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
2019-07-24 15:45:46+0000 [-]     raise value
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2549, in _flush
2019-07-24 15:45:46+0000 [-]     flush_context.execute()
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
2019-07-24 15:45:46+0000 [-]     rec.execute(self)
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
2019-07-24 15:45:46+0000 [-]     uow,
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
2019-07-24 15:45:46+0000 [-]     insert,
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1120, in _emit_insert_statements
2019-07-24 15:45:46+0000 [-]     statement, params
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
2019-07-24 15:45:46+0000 [-]     return meth(self, multiparams, params)
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
2019-07-24 15:45:46+0000 [-]     return connection._execute_clauseelement(self, multiparams, params)
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
2019-07-24 15:45:46+0000 [-]     distilled_params,
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
2019-07-24 15:45:46+0000 [-]     e, statement, parameters, cursor, context
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
2019-07-24 15:45:46+0000 [-]     util.raise_from_cause(sqlalchemy_exception, exc_info)
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
2019-07-24 15:45:46+0000 [-]     reraise(type(exception), exception, tb=exc_tb, cause=cause)
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
2019-07-24 15:45:46+0000 [-]     raise value.with_traceback(tb)
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
2019-07-24 15:45:46+0000 [-]     cursor, statement, parameters, context
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
2019-07-24 15:45:46+0000 [-]     cursor.execute(statement, parameters)
2019-07-24 15:45:46+0000 [-] sqlalchemy.exc.DataError: (psycopg2.DataError) integer out of range
2019-07-24 15:45:46+0000 [-]
2019-07-24 15:45:46+0000 [-] [SQL: INSERT INTO image_packages (image_id, image_user_id, name, version, pkg_type, arch, pkg_path, pkg_path_hash, distro_name, distro_version, like_distro, fullversion, release, origin, src_pkg, normalized_src_pkg, metadata_json, license, size, created_at, updated_at) VALUES (%(image_id)s, %(image_user_id)s, %(name)s, %(version)s, %(pkg_type)s, %(arch)s, %(pkg_path)s, %(pkg_path_hash)s, %(distro_name)s, %(distro_version)s, %(like_distro)s, %(fullversion)s, %(release)s, %(origin)s, %(src_pkg)s, %(normalized_src_pkg)s, %(metadata_json)s, %(license)s, %(size)s, %(created_at)s, %(updated_at)s)]
2019-07-24 15:45:46+0000 [-] [parameters: {'image_id': 'a34743cbdafc54ab37746750d489ba847fdc479d8861ef976281b2b00c22ee5b', 'image_user_id': 'admin', 'name': 'storcli', 'version': '007.0415.0000.0000', 'pkg_type': 'dpkg', 'arch': 'all', 'pkg_path': 'pkgdb', 'pkg_path_hash': None, 'distro_name': 'ubuntu', 'distro_version': '18.04', 'like_distro': 'debian', 'fullversion': '007.0415.0000.0000', 'release': 'N/A', 'origin': 'OS-Utils  <bangalore-mr-osutils.pdl@avagotech.com> (maintainer)', 'src_pkg': 'storcli-007.0415.0000.0000', 'normalized_src_pkg': 'storcli', 'metadata_json': None, 'license': 'Unknown', 'size': 7000000000, 'created_at': datetime.datetime(2019, 7, 24, 15, 45, 46, 236596), 'updated_at': datetime.datetime(2019, 7, 24, 15, 45, 46, 236603)}]
2019-07-24 15:45:46+0000 [-] (Background on this error at: http://sqlalche.me/e/9h9h)
2019-07-24 15:45:46+0000 [_GenericHTTPChannelProtocol,367,172.18.0.7] [PoolThread-twisted.internet.reactor-0] [anchore_engine.services.policy_engine.api.controllers.synchronous_operations/ingress_image()] [ERROR] Error loading image into
policy engine
```
**Relevant Logs from analyzer**
```
2019-07-24 15:45:27+0000 [-] [Thread-10632] [anchore_engine.services.analyzer/process_analyzer_job()] [INFO] image dequeued for analysis: admin : sha256:a3d5e581f34d2275c57073a086604930feb0b55511cefcc8293ddd4bd966a47f
2019-07-24 15:45:27+0000 [-] [Thread-10632] [anchore_engine.services.analyzer/perform_analyze_nodocker()] [INFO] performing analysis on image: ['admin', 'gitlab-master.internal.com:5005/pstooling/utilities/storcli@sha256:a3d5e581f34d2275c57
073a086604930feb0b55511cefcc8293ddd4bd966a47f', 'gitlab-master.internal.com:5005/pstooling/utilities/storcli:latest']
2019-07-24 15:45:43+0000 [-] "127.0.0.1" - - [24/Jul/2019:15:45:43 +0000] "GET /health HTTP/1.1" 200 - "-" "curl/7.29.0"
2019-07-24 15:45:44+0000 [-] [Thread-10632] [anchore_engine.services.analyzer/perform_analyze_nodocker()] [INFO] performing analysis on image complete: gitlab-master.internal.com:5005/pstooling/utilities/storcli@sha256:a3d5e581f34d2275c5707
3a086604930feb0b55511cefcc8293ddd4bd966a47f
2019-07-24 15:45:45+0000 [-] [Thread-10632] [anchore_engine.services.analyzer/process_analyzer_job()] [INFO] Loading image into policy engine: admin a34743cbdafc54ab37746750d489ba847fdc479d8861ef976281b2b00c22ee5b
2019-07-24 15:45:46+0000 [-] [Thread-10632] [anchore_engine.clients.services.internal/dispatch()] [ERROR] Failed client call to service policy_engine for url: http://engine-policy-engine:8228/v1/images. Response: {'httpcode': 500, 'anchor
e_error_raw': 'b\'{\\n  "detail": {\\n    "error_codes": []\\n  },\\n  "httpcode": 500,\\n  "message": "(psycopg2.DataError) integer out of range\\\\n\\\\n[SQL: INSERT INTO image_packages (image_id, image_user_id, name, version, pkg_type,
 arch, pkg_path, pkg_path_hash, distro_name, distro_version, like_distro, fullversion, release, origin, src_pkg, normalized_src_pkg, metadata_json, license, size, created_at, updated_at) VALUES (%(image_id)s, %(image_user_id)s, %(name)s,
%(version)s, %(pkg_type)s, %(arch)s, %(pkg_path)s, %(pkg_path_hash)s, %(distro_name)s, %(distro_version)s, %(like_distro)s, %(fullversion)s, %(release)s, %(origin)s, %(src_pkg)s, %(normalized_src_pkg)s, %(metadata_json)s, %(license)s, %(s
ize)s, %(created_at)s, %(updated_at)s)]\\\\n[parameters: {\\\'image_id\\\': \\\'a34743cbdafc54ab37746750d489ba847fdc479d8861ef976281b2b00c22ee5b\\\', \\\'image_user_id\\\': \\\'admin\\\', \\\'name\\\': \\\'storcli\\\', \\\'version\\\': \\
\'007.0415.0000.0000\\\', \\\'pkg_type\\\': \\\'dpkg\\\', \\\'arch\\\': \\\'all\\\', \\\'pkg_path\\\': \\\'pkgdb\\\', \\\'pkg_path_hash\\\': None, \\\'distro_name\\\': \\\'ubuntu\\\', \\\'distro_version\\\': \\\'18.04\\\', \\\'like_distro
\\\': \\\'debian\\\', \\\'fullversion\\\': \\\'007.0415.0000.0000\\\', \\\'release\\\': \\\'N/A\\\', \\\'origin\\\': \\\'OS-Utils  <bangalore-mr-osutils.pdl@avagotech.com> (maintainer)\\\', \\\'src_pkg\\\': \\\'storcli-007.0415.0000.0000\
\\', \\\'normalized_src_pkg\\\': \\\'storcli\\\', \\\'metadata_json\\\': None, \\\'license\\\': \\\'Unknown\\\', \\\'size\\\': 7000000000, \\\'created_at\\\': datetime.datetime(2019, 7, 24, 15, 45, 46, 236596), \\\'updated_at\\\': datetim
e.datetime(2019, 7, 24, 15, 45, 46, 236603)}]\\\\n(Background on this error at: http://sqlalche.me/e/9h9h)"\\n}\\n\'', 'anchore_error_json': {'detail': {'error_codes': []}, 'httpcode': 500, 'message': "(psycopg2.DataError) integer out of
range\n\n[SQL: INSERT INTO image_packages (image_id, image_user_id, name, version, pkg_type, arch, pkg_path, pkg_path_hash, distro_name, distro_version, like_distro, fullversion, release, origin, src_pkg, normalized_src_pkg, metadata_json
, license, size, created_at, updated_at) VALUES (%(image_id)s, %(image_user_id)s, %(name)s, %(version)s, %(pkg_type)s, %(arch)s, %(pkg_path)s, %(pkg_path_hash)s, %(distro_name)s, %(distro_version)s, %(like_distro)s, %(fullversion)s, %(rel
ease)s, %(origin)s, %(src_pkg)s, %(normalized_src_pkg)s, %(metadata_json)s, %(license)s, %(size)s, %(created_at)s, %(updated_at)s)]\n[parameters: {'image_id': 'a34743cbdafc54ab37746750d489ba847fdc479d8861ef976281b2b00c22ee5b', 'image_user
_id': 'admin', 'name': 'storcli', 'version': '007.0415.0000.0000', 'pkg_type': 'dpkg', 'arch': 'all', 'pkg_path': 'pkgdb', 'pkg_path_hash': None, 'distro_name': 'ubuntu', 'distro_version': '18.04', 'like_distro': 'debian', 'fullversion':
'007.0415.0000.0000', 'release': 'N/A', 'origin': 'OS-Utils  <bangalore-mr-osutils.pdl@avagotech.com> (maintainer)', 'src_pkg': 'storcli-007.0415.0000.0000', 'normalized_src_pkg': 'storcli', 'metadata_json': None, 'license': 'Unknown', 's
ize': 7000000000, 'created_at': datetime.datetime(2019, 7, 24, 15, 45, 46, 236596), 'updated_at': datetime.datetime(2019, 7, 24, 15, 45, 46, 236603)}]\n(Background on this error at: http://sqlalche.me/e/9h9h)"}}
2019-07-24 15:45:46+0000 [-] Traceback (most recent call last):
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/analyzer/__init__.py", line 199, in process_analyzer_job
2019-07-24 15:45:46+0000 [-]     resp = pe_client.ingress_image(userId, imageId, image_analysis_fetch_url)
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/services/policy_engine.py", line 14, in ingress_image
2019-07-24 15:45:46+0000 [-]     return self.call_api(anchy_post, 'images', body=json.dumps({'user_id': user_id, 'image_id': image_id, 'fetch_url': analysis_fetch_url}))
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/services/internal.py", line 152, in call_api
2019-07-24 15:45:46+0000 [-]     return self.dispatch(base_url, method, path, path_params, query_params, extra_headers, body, connect_timeout, read_timeout)
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/services/internal.py", line 204, in dispatch
2019-07-24 15:45:46+0000 [-]     raise e
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/services/internal.py", line 201, in dispatch
2019-07-24 15:45:46+0000 [-]     return method(url=final_url, headers=request_headers, data=body, auth=(self.user, self.password), params=filtered_qry_params, verify=self.verify_ssl)
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/services/http.py", line 269, in anchy_post
2019-07-24 15:45:46+0000 [-]     raise e
2019-07-24 15:45:46+0000 [-] Exception: failed post url=http://engine-policy-engine:8228/v1/images
2019-07-24 15:45:46+0000 [-]
2019-07-24 15:45:46+0000 [-] During handling of the above exception, another exception occurred:
2019-07-24 15:45:46+0000 [-]
2019-07-24 15:45:46+0000 [-] Traceback (most recent call last):
2019-07-24 15:45:46+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/analyzer/__init__.py", line 205, in process_analyzer_job
2019-07-24 15:45:46+0000 [-]     raise newerr
2019-07-24 15:45:46+0000 [-] anchore_engine.services.analyzer.PolicyEngineClientError: Adding image to policy-engine failed - exception: failed post url=http://engine-policy-engine:8228/v1/images
2019-07-24 15:45:46+0000 [-] [Thread-10632] [anchore_engine.services.analyzer/process_analyzer_job()] [ERROR] problem analyzing image - exception: Adding image to policy-engine failed - exception: failed post url=http://engine-policy-engine:8228/v1/images
```

**Relevant DPKG Listing for File that is apparently involved**
```
apt-cache show storcli
Package: storcli
Status: install ok installed
Priority: optional
Section: storcli
Installed-Size: 7000000
Maintainer: OS-Utils  <bangalore-mr-osutils.pdl@avagotech.com>
Architecture: all
Version: 007.0415.0000.0000
Depends: bash
Description: Storage Command Line Tool, manages storage controllers.
Description-md5: 6de2cb6a23d424faa8f376e70efa5f08
```

**What docker images are you using**:
`ubuntu:18.04` is the base. You have to add a single **debian file** 

**How to reproduce the issue**:
Acquire the `storcli` binary from https://downloadcenter.intel.com/download/27654/StorCLI-Standalone-Utility (pull storcli_007.0415.0000.0000_all.deb from the zip)
The following dockerfile was used to create the issue

```dockerfile
FROM ubuntu:18.04

ADD storcli_007.0415.0000.0000_all.deb /opt/
RUN set -ex && dpkg -i /opt/storcli_007.0415.0000.0000_all.deb
```

**Anything else we need to know**:
As you can see from dpkg, the installed size is **7000000**, but in the post to the policy engine, the size comes across as **_7000000000_** which by the error message is too large.

**Comment by nurmi** [comment]
hi @adawalli - thank you for the report!

There are a couple of interesting things going in here :)  First though, this is an pretty straightforward update to anchore-engine to support packages that are (wow) reporting as installing over 2GB of files, which we will work into a future release of anchore-engine by changing the column type for the package record.

Information-wise, I've investigated a bit - that package is incorrectly claiming a 7GB installation (the unit of the Installed-Size control field of a dpkg is kilobytes, and indeed the package is reporting '7000000' kilobytes (7 gigabytes) which is inaccurate - I installed the package and looked at the files to verify that it is only using a few tens of megabytes.  Anchore is storing package sizes in bytes, so it takes the reported kilobyte value and multiplies it by ~1k to get back to bytes.

We'll keep the ticket open to track the top-level enhancement of allowing anchore to handle packages that are reporting a >2GB installation size, and will post progress here!

**Comment by adawalli** [comment]
Thanks @nurmi! I see - the debian package is itself reporting the size incorrectly? If so, I mistakenly made the assumption that the analyzer had misread the information.

Thanks for your detailed response!

**Comment by nurmi** [comment]
I believe that the package is reporting incorrectly (however, we still want to make a change to anchore to support larger package sizes (right now, the limit will be 2GB).  I'm getting this from:

```
# dpkg-query -W -f '${Installed-Size}' storcli 
7000000
```

crossed with this (odd description of kilobyte, but kilobyte non-the-less :):

https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-installed-size

crossed with this:

```
# dpkg-query -L storcli
/.
/opt
/opt/MegaRAID
/opt/MegaRAID/storcli
/opt/MegaRAID/storcli/storcli
/opt/MegaRAID/storcli/storcli64
# du -h --max-depth=0 /opt/MegaRAID/
18M	/opt/MegaRAID/
```

**Comment by adawalli** [comment]
ok, thanks so much for explaining! I will do what I can locally to remove that package for now but also look forward to the change allowing larger binaries (fake larger binaries included ;) )
