### ISSUE TITLE
Initial feed sync never completes

### ISSUE THREAD

**Issue by dcherniv** [anchore/anchore-engine#246]
**Version of Anchore Engine and Anchore CLI if applicable**:
```
sh-4.2$ anchore-cli --version
anchore-cli, version 0.4.1
sh-4.2$ 
kubectl get pods -n devops -o yaml devops-anchore-anchore-engine-api-8685d64f56-fj82k | grep image
    image: docker.io/anchore/anchore-engine:v0.4.2
    imagePullPolicy: IfNotPresent
    image: anchore/anchore-engine:v0.4.2
    imageID: docker-pullable://anchore/anchore-engine@sha256:17b1ec4fd81193b2d5e371aeb5fc00775725f17af8338b4a1d4e1731dd69df6f
```
 
**What happened**:
Feed sync timeout connecting to https://ancho.re
Some feeds are never synced. Been sitting in the same state for 2 days now. Output from system feeds list:
```
Feed                   Group                  LastSync                          RecordCount
nvd                    nvddb:2002             2019-08-05T12:46:17.190987        6746
nvd                    nvddb:2003             2019-08-05T12:48:00.441942        1547
nvd                    nvddb:2004             2019-08-05T12:47:17.441528        2702
nvd                    nvddb:2005             2019-08-04T07:25:52.153198        4750
nvd                    nvddb:2006             2019-08-04T16:54:02.414968        7128
nvd                    nvddb:2007             2019-08-05T06:23:40.738775        6558               
nvd                    nvddb:2008             2019-08-04T16:55:54.041857        7147               
nvd                    nvddb:2009             2019-08-04T16:57:46.629574        4967               
nvd                    nvddb:2010             2019-08-05T06:38:40.440354        5078               
nvd                    nvddb:2011             None                              0                  
nvd                    nvddb:2012             2019-08-05T12:44:36.179031        5552               
nvd                    nvddb:2013             None                              0                  
nvd                    nvddb:2014             2019-08-05T12:45:24.073597        8517               
nvd                    nvddb:2015             None                              0                  
nvd                    nvddb:2016             None                              0                  
nvd                    nvddb:2017             None                              0                  
nvd                    nvddb:2018             None                              0                  
nvd                    nvddb:2019             None                              0                  
vulnerabilities        alpine:3.10            2019-08-05T14:44:20.875350        1370               
vulnerabilities        alpine:3.3             2019-08-05T14:45:04.044034        457                
vulnerabilities        alpine:3.4             2019-08-05T14:45:46.889348        681                
vulnerabilities        alpine:3.5             2019-08-05T14:46:28.705803        875                
vulnerabilities        alpine:3.6             2019-08-05T14:47:08.753931        1051               
vulnerabilities        alpine:3.7             2019-08-05T14:48:26.587602        1194               
vulnerabilities        alpine:3.8             2019-08-05T14:49:05.561149        1274               
vulnerabilities        alpine:3.9             2019-08-05T14:49:43.980931        1305               
vulnerabilities        amzn:2                 2019-08-05T14:50:25.961002        194                
vulnerabilities        centos:5               2019-08-05T14:47:45.841475        1324               
vulnerabilities        centos:6               2019-08-05T14:51:46.393026        1347               
vulnerabilities        centos:7               2019-08-05T14:52:32.709745        814                
vulnerabilities        centos:8               2019-08-05T14:51:07.864007        48                 
vulnerabilities        debian:10              2019-08-05T14:53:08.390491        20750              
vulnerabilities        debian:7               2019-08-05T14:18:35.100422        20455              
vulnerabilities        debian:8               2019-08-05T14:19:15.948652        22144              
[...]
```

**What did you expect to happen**:
Feeds to be synced within reasonable time frame. a day?

**Any relevant log output from /var/log/anchore**:
```
[service:policy-engine] 2019-08-05 15:15:37+0000 [-] "172.16.127.250" - - [05/Aug/2019:15:15:36 +0000] "GET /v1/feeds?include_counts=True HTTP/1.1" 200 6877 "-" "python-requests/2.20.0"
[service:policy-engine] 2019-08-05 15:16:34+0000 [-] Traceback (most recent call last):
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds.py", line 825, in _sync_group
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]     new_data_deduped, next_token = self._get_deduped_data(group_obj, since=last_sync, next_token=next_token, max_pages=self.MAX_FEED_SYNC_PAGES)
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds.py", line 753, in _get_deduped_data
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]     next_token=next_token)
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds.py", line 490, in get_paged_feed_group_data
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]     resp = self.client.get_feed_group_data(feed, group, next_token=next_token)
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/feeds/feed_service.py", line 162, in get_feed_group_data
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]     raise e
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/feeds/feed_service.py", line 159, in get_feed_group_data
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]     record.get('text')))
[service:policy-engine] 2019-08-05 15:16:34+0000 [-] Exception: Feed list operation failed. Msg: None. Response: server error: HTTPSConnectionPool(host='ancho.re', port=443): Read timed out. (read timeout=60)
[service:policy-engine] 2019-08-05 15:16:34+0000 [-] [Thread-11] [anchore_engine.services.policy_engine.engine.logs/exception()] [ERROR] Error syncing group: <<class 'anchore_engine.db.entities.policy_engine.FeedGroupMetadata'> name=nvddb:2016, feed=nvd, access_tier=0, created_at=2019-08-02 14:20:40.366747>
[service:policy-engine] 2019-08-05 15:16:34+0000 [-] [Thread-11] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Syncing group took 400.1416962146759 sec
[service:policy-engine] 2019-08-05 15:16:34+0000 [-] Traceback (most recent call last):
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds.py", line 972, in sync
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]     new_data = self._sync_group(g, full_flush=full_flush)  # Each group sync is a transaction
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds.py", line 825, in _sync_group
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]     new_data_deduped, next_token = self._get_deduped_data(group_obj, since=last_sync, next_token=next_token, max_pages=self.MAX_FEED_SYNC_PAGES)
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds.py", line 753, in _get_deduped_data
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]     next_token=next_token)
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds.py", line 490, in get_paged_feed_group_data
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]     resp = self.client.get_feed_group_data(feed, group, next_token=next_token)
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/feeds/feed_service.py", line 162, in get_feed_group_data
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]     raise e
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/feeds/feed_service.py", line 159, in get_feed_group_data
[service:policy-engine] 2019-08-05 15:16:34+0000 [-]     record.get('text')))
[service:policy-engine] 2019-08-05 15:16:34+0000 [-] Exception: Feed list operation failed. Msg: None. Response: server error: HTTPSConnectionPool(host='ancho.re', port=443): Read timed out. (read timeout=60)
[service:policy-engine] 2019-08-05 15:16:34+0000 [-] [Thread-11] [anchore_engine.services.policy_engine.engine.logs/exception()] [ERROR] Failed syncing group data for nvd/nvddb:2016
[service:policy-engine] 2019-08-05 15:16:34+0000 [-] [Thread-11] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Processing group: nvddb:2017
[service:policy-engine] 2019-08-05 15:17:45+0000 [-] "172.16.127.250" - - [05/Aug/2019:15:17:44 +0000] "GET /v1/feeds?include_counts=True HTTP/1.1" 200 6877 "-" "python-requests/2.20.0"
```

**What docker images are you using**:
0.4.2 official helm chart.

**How to reproduce the issue**:
Install the helm chart and switch the backend from db to s3. Use external postgres endpoint (RDS in AWS), which were the only customizations applied to the chart.

**Anything else we need to know**:
No.

**Comment by dcherniv** [comment]
Some more information. I can confirm that the ancho.re is reacheable from within the container. Though it appears to be very slow.
```
sh-4.2$ time curl https://ancho.re
{
    "jse_shortmsg": "/ does not exist",
    "jse_info": {},
    "message": "/ does not exist",
    "statusCode": 404,
    "body": {
        "code": "ResourceNotFound",
        "message": "/ does not exist"
    },
    "restCode": "ResourceNotFound"
}
real    0m7.223s
user    0m0.036s
sys     0m0.115s
sh-4.2$ 
```

**Comment by nurmi** [comment]
@dcherniv ,

Thank you for the report!  We've been observing some infra problems on the back-end services that are hosted at ancho.re.  We believe that the issue has been resolved as of this 20-30 minutes prior to this comment, and you should see better performance/no timeouts now. 

We're going to continue to investigate the cause of the troubles as well, to try annd prevent these types of interruptions from occurring in the future.

**Comment by dcherniv** [comment]
Yep everything is in order now. Closing.

**Comment by cramakan** [comment]
getting  error on  link https://ancho.re/   404 Not Found
nginx/1.10.3 (Ubuntu)
