### ISSUE TITLE
Failed client call to service simple queues

### ISSUE THREAD

**Issue by milijander88** [anchore/anchore-engine#251]
Hi all,

I am get this error: 

> Failed client call to service simplequeue for url: http://localhost:8228/v1/queues/watcher_tasks/is_inqueue . Response: {'httpcode': 404, 'anchore_error_raw': 'b\'{\\n  "detail": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.",\\n  "status": 404,\\n  "title": "Not Found",\\n  "type": "about:blank"\\n}\\n\'', 'anchore_error_json': {'detail': 'The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.', 'status': 404, 'title': 'Not Found', 'type': 'about:blank'}}

when I tried to run Anchore engine on minishift.

 I am pulling image from registry.connect.redhat.com/anchore/engine4 on my minishift , but I first configured postgresql db on minishift and anchore can access to postgresql.

>         name anchore-engine
>         vendor Anchore Inc.
>         version 0.4.2
>         release r0

**Comment by nurmi** [comment]
hi @milijander88 

Can you describe in a bit more detail exactly how you are configuring/deploying anchore-engine?  That error is indicating that perhaps the config.yaml in place is registering a simplequeue service on 'localhost:8228' but that won't work as an endpoint for the worker, unless the services are co-located and not using the same port - if we can review your config/deployment scripts and setup, we should be able to help!

**Comment by milijander88** [comment]
Hi @nurmi  I am using minishift, and openshift cluster for anchore, but for now I am configuring anchore engine on minishfit and this is my setup.

I am using  **PostgreSQL 10 SQL database server**  that I pulled from:
 **registry.redhat.io/rhscl/postgresql-10-rhel7** and I use Deploy image on minishift to import Postgresql and then I configure env variable for postgresql (POSTGRESQL_USER, POSTGRESQL_PASSWORD and POSTGRESQL_DATABASE). After I configure postgresql I imported Anchore engine in minishift from registry.connect.redhat.com/anchore/engine4 using  Deploy image on minishift and configured env variable. 

I am using this Docker image :
https://access.redhat.com/containers/?architecture&tab=docker-file#/registry.connect.redhat.com/anchore/engine4/images/v0.4.2-r0

This is deployment script from openshift:


```
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2019-07-25T11:36:25Z'
  generation: 18
  labels:
    app: engine4
  name: engine4
  namespace: mbl-test
  resourceVersion: '48069233'
  selfLink: /apis/apps.openshift.io/v1/namespaces/mbsl-testsdf/deploymentconfigs/engine4
  uid: 6f94c3eb-aed0-11e9-8c30-0a9cd92e7c86
spec:
  replicas: 1
  selector:
    app: engine4
    deploymentconfig: engine4
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: engine4
        deploymentconfig: engine4
    spec:
      containers:
        - env:
            - name: ANCHORE_DB_HOST
              value: postgresql-10-rhel7.mbl-test.svc
            - name: ANCHORE_DB_PASSWORD
              value: foobar
            - name: ANCHORE_DB_POSTGRESQL_SERVICE_PORT
              value: '5432'
            - name: ANCHORE_ENGINE_SERVICE_SERVICE_HOST
              value: anchore.example.com
            - name: ANCHORE_HOST_ID
              value: anchore-dev
            - name: ANCHORE_CLI_SSL_VERIFY
              value: 'n'
            - name: ANCHORE_CLI_URL
              value: 'http://localhost:8228/v1'
            - name: ANCHORE_ENDPOINT_HOSTNAME
              value: engine-catalog
          image: >-
            registry.connect.redhat.com/anchore/engine4@sha256:2a0f686711sdfsdf71617da8d666a1124950a9270f1917ca98139d84357217a8dbededc
          imagePullPolicy: Always
          name: engine4
          ports:
            - containerPort: 8228
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 600Mi
            requests:
              cpu: 400m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - engine4
        from:
          kind: ImageStreamTag
          name: 'engine4:latest'
          namespace: mbl-test
        lastTriggeredImage: >-
          registry.connect.redhat.com/anchore/engine4@sha256:2a0f686711sdfsdf71617da8d666a1124950a9270f1917ca98139d84357217a8dbededc
      type: ImageChange
status:
  availableReplicas: 0
  conditions:
    - lastTransitionTime: '2019-07-30T08:51:18Z'
      lastUpdateTime: '2019-07-30T08:51:18Z'
      message: replication controller "engine4-10" has failed progressing
      reason: ProgressDeadlineExceeded
      status: 'False'
      type: Progressing
    - lastTransitionTime: '2019-08-09T06:50:24Z'
      lastUpdateTime: '2019-08-09T06:50:24Z'
      message: Deployment config does not have minimum availability.
      status: 'False'
      type: Available
  details:
    causes:
      - type: ConfigChange
    message: config change
  latestVersion: 10
  observedGeneration: 18
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 0
```

**Comment by milijander88** [comment]
Hi all,

Now I  am facing with this issue, when I try to run anchore engine on openshift?

```

Traceback (most recent call last):
--
  | File "/opt/rh/rh-python36/root/usr/bin/twistd", line 11, in <module>
  | sys.exit(run())
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/twisted/scripts/twistd.py", line 31, in run
  | app.run(runApp, ServerOptions)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/twisted/application/app.py", line 674, in run
  | runApp(config)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/twisted/scripts/twistd.py", line 25, in runApp
  | runner.run()
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/twisted/application/app.py", line 383, in run
  | self.logger.start(self.application)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/twisted/application/app.py", line 184, in start
  | observer = self._observerFactory()
  | File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/subsys/twistd_logger.py", line 14, in logger
  | f = logfile.LogFile(thefile, '/var/log/', rotateLength=10000000, maxRotatedFiles=10)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/twisted/python/logfile.py", line 170, in __init__
  | BaseLogFile.__init__(self, name, directory, defaultMode)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/twisted/python/logfile.py", line 45, in __init__
  | self._openFile()
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/twisted/python/logfile.py", line 175, in _openFile
  | BaseLogFile._openFile(self)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/twisted/python/logfile.py", line 85, in _openFile
  | self._file = open(self.path, "wb+", 0)
  | PermissionError: [Errno 13] Permission denied: '/var/log/anchore/anchore-catalog.log'
  | [MainThread] [anchore_manager.cli.service/start()] [INFO] Loading DB routines from module (anchore_engine)
  | [MainThread] [anchore_manager.cli.utils/connect_database()] [INFO] DB params: {"db_connect_args": {"connect_timeout": 86400}, "db_pool_size": 30, "db_pool_max_overflow": 100, "db_echo": false}
  | [MainThread] [anchore_manager.cli.utils/connect_database()] [INFO] DB connection configured: True
  | [MainThread] [anchore_manager.cli.utils/connect_database()] [INFO] DB attempting to connect...
  | [MainThread] [anchore_manager.cli.utils/connect_database()] [INFO] DB connected: True
  | [MainThread] [anchore_manager.cli.utils/init_database()] [INFO] DB compatibility check: running...
  | [MainThread] [anchore_manager.cli.utils/init_database()] [INFO] DB compatibility check success
  | [MainThread] [anchore_manager.cli.utils/init_database()] [INFO] DB post actions: running...
  | [MainThread] [anchore_manager.cli.service/start()] [INFO] DB version and code version in sync.
  | [MainThread] [anchore_manager.cli.service/start()] [INFO] Starting services: ['anchore-catalog', 'anchore-api', 'anchore-kubernetes-webhook', 'anchore-simplequeue', 'anchore-worker', 'anchore-policy-engine']
  | [MainThread] [anchore_manager.cli.service/terminate_service()] [INFO] Looking for pre-existing service (anchore-catalog) pid from pidfile (/var/run/anchore/anchore-catalog.pid)
  | [anchore-catalog] [anchore_manager.cli.service/startup_service()] [INFO] cleaning up service: anchore-catalog
  | [MainThread] [anchore_manager.cli.service/start()] [INFO] waiting for service pidfile /var/run/anchore/anchore-catalog.pid to exist 0/30
  | [anchore-catalog] [anchore_manager.cli.service/terminate_service()] [INFO] Looking for pre-existing service (anchore-catalog) pid from pidfile (/var/run/anchore/anchore-catalog.pid)
  | [anchore-catalog] [anchore_manager.cli.service/startup_service()] [INFO] starting service: anchore-catalog
  | [anchore-catalog] [anchore_manager.cli.service/startup_service()] [INFO] 	 twistd --logger=anchore_engine.subsys.twistd_logger.logger --pidfile /var/run/anchore/anchore-catalog.pid -n anchore-catalog --config /config
  | [MainThread] [anchore_manager.cli.service/start()] [INFO] waiting for service pidfile /var/run/anchore/anchore-catalog.pid to exist 1/30
  | [MainThread] [anchore_manager.cli.service/start()] [INFO] waiting for service pidfile /var/run/anchore/anchore-catalog.pid to exist 2/30
  | Traceback (most recent call last):
  | File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_manager/cli/service.py", line 167, in startup_service
  | raise Exception("process exited: " + str(rc))
  | Exception: process exited: 1
  | [anchore-catalog] [anchore_manager.cli.service/startup_service()] [ERROR] service process exited at (Mon Aug 19 12:11:29 2019): process exited: 1
  | [anchore-catalog] [anchore_manager.cli.service/startup_service()] [FATAL] Could not start service due to: process exited: 1
  | [anchore-catalog] [anchore_manager.cli.service/startup_service()] [INFO] exiting service thread
  | [MainThread] [anchore_manager.cli.service/start()] [INFO] waiting for service pidfile /var/run/anchore/anchore-catalog.pid to exist 3/30
  | [MainThread] [anchore_manager.cli.service/start()] [INFO] service thread has stopped anchore-catalog
  | [MainThread] [anchore_manager.cli.service/start()] [INFO] auto_restart_services setting: False
  | [MainThread] [anchore_manager.cli.service/start()] [INFO] checking for startup failure pidfile=False, is_alive=False
  | [MainThread] [anchore_manager.cli.service/start()] [WARN] service start failed - exception: service thread for (anchore-catalog) failed to start
  | [MainThread] [anchore_manager.cli.service/start()] [FATAL] one or more services failed to start. cleanly terminating the others
  | [MainThread] [anchore_manager.cli.service/terminate_service()] [INFO] Looking for pre-existing service (anchore-catalog) pid from pidfile (/var/run/anchore/anchore-catalog.pid)
  | [MainThread] [anchore_manager.cli.service/terminate_service()] [INFO] Looking for pre-existing service (anchore-api) pid from pidfile (/var/run/anchore/anchore-api.pid)
  | [MainThread] [anchore_manager.cli.service/terminate_service()] [INFO] Looking for pre-existing service (anchore-kubernetes-webhook) pid from pidfile (/var/run/anchore/anchore-kubernetes-webhook.pid)
  | [MainThread] [anchore_manager.cli.service/terminate_service()] [INFO] Looking for pre-existing service (anchore-simplequeue) pid from pidfile (/var/run/anchore/anchore-simplequeue.pid)
  | [MainThread] [anchore_manager.cli.service/terminate_service()] [INFO] Looking for pre-existing service (anchore-worker) pid from pidfile (/var/run/anchore/anchore-worker.pid)
  | [MainThread] [anchore_manager.cli.service/terminate_service()] [INFO] Looking for pre-existing service (anchore-policy-engine) pid from pidfile (/var/run/anchore/anchore-policy-engine.pid)

```

**Comment by nurmi** [comment]
Hi @milijander88 - we'll be looking into this particular way of deploying the engine into oshift, as our investigations so far using that same image (deploying it into k8s, with docker-compose, etc) are not showing any issues.  Something is preventing the container from writing its logfiles to the local /var/log/anchore/ directory (anchore services come up and run as the 'anchore' user, and the container image has those locations owned by anchore:anchore, so we're not sure why there would be a permissions issue there).  We'll follow up if we can have some findings, but in your own investigation I'd suggest looking into that area.

**Comment by zhill** [comment]
@milijander88 I suggest using a localdir volume mounted at /var/log/anchore/ in the container. It looks like the container does not have write permission to the FS inside the container so you using a volume there should help resolve that.

**Comment by jesseadams** [comment]
:+1: Having the same `Permission denied` issue following https://anchore.com/running-anchore-engine-on-openshift/

**Comment by jesseadams** [comment]
@milijander88 - I was able to resolve this permissions issue. Apparently @zhill was on the money. Per https://anchore.com/how-tremolo-security-deploys-anchore-on-openshift/:

> The containers that make up Anchore’s engine write ephemeral data into their containers. Most k8s distros will let you do this based on file system permissions, but not OKD. When you need to write ephemeral data you need to update your pods to use empty volumes.

In order to get this resolved, I had to update each deployment config with the following additions:

Under volumeMounts:
```
            - mountPath: /var/log/anchore
              name: logs
            - mountPath: /var/run
              name: run
```

Under volumes:
```
        - emptyDir: {}
          name: logs
        - emptyDir: {}
          name: run
```

@nurmi - It may be worth taking the time to explicitly call this out in the following places:
* https://anchore.com/running-anchore-engine-on-openshift/
* https://github.com/helm/charts/tree/master/stable/anchore-engine

**Comment by zhill** [comment]
The updated helm chart (https://github.com/helm/charts/commit/304cc943e6d34c707cea562524e2788d333ce3ef) supports this out of the box. See the chart's [README](https://github.com/helm/charts/tree/master/stable/anchore-engine#installing-on-openshift) for openshift installs. I'm going to close this issue, but please re-open if needed.
