### ISSUE TITLE
Image add using admission-controller doesn't work

### ISSUE THREAD

**Issue by brennoo** [anchore/anchore-engine#256]
I'm currently running anchore-engine using the public helm chart and aws ECR repository added using IAM auth.
anchore-cli image add *does* works, eg:

`anchore-cli image add 1234567890.dkr.ecr.eu-west-1.amazonaws.com/my-app-name:b076ab4`

I can also see in the catalog logs:
```
[service:catalog] 2019-08-21 10:19:27+0000 [-] [Thread-1088017] [anchore_engine.services.catalog/handle_repo_watcher()] [DEBUG] FIRING: handle_repo_watcher
[service:catalog] 2019-08-21 10:19:27+0000 [-] [Thread-1088017] [anchore_engine.services.catalog.catalog_impl/refresh_registry_creds()] [DEBUG] checking registry for up-to-date: admin : 1234567890.dkr.ecr.eu-west-1.amazonaws.com : awsecr
[service:catalog] 2019-08-21 10:19:27+0000 [-] [Thread-1088017] [anchore_engine.services.catalog.catalog_impl/refresh_registry_creds()] [DEBUG] registry up-to-date: admin : 1234567890.dkr.ecr.eu-west-1.amazonaws.com : awsecr
[service:catalog] 2019-08-21 10:19:27+0000 [-] [Thread-1088017] [anchore_engine.services.catalog/handle_repo_watcher()] [DEBUG] FIRING DONE: handle_repo_watcher
[service:catalog] 2019-08-21 10:19:27+0000 [-] [Thread-11] [anchore_engine.clients.services.simplequeue/run_target_with_lease()] [DEBUG] Target thread returned
```

When I started testing the admission-controller the calls to add images fails and I can see in the catalog logs:
```[service:catalog] 2019-08-21 10:21:04+0000 [_GenericHTTPChannelProtocol,156582,10.3.27.193] [PoolThread-twisted.internet.reactor-2] [anchore_engine.clients.skopeo_wrapper/get_image_manifest_skopeo_raw()] [ERROR] command failed with exception - Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  inspect --raw --tls-verify=false  docker://1234567890.dkr.ecr.eu-west-1.amazonaws.com/my-app-name:b076ab4, rc=1, stdout=None, stderr=b'time="2019-08-21T10:21:04Z" level=fatal msg="Error reading manifest b076ab4 in 1234567890.dkr.ecr.eu-west-1.amazonaws.com/my-app-name: unauthorized: authentication required" \n', error_code=REGISTRY_PERMISSION_DENIED
[service:catalog] 2019-08-21 10:21:04+0000 [_GenericHTTPChannelProtocol,156582,10.3.27.193] [PoolThread-twisted.internet.reactor-2] [anchore_engine.clients.skopeo_wrapper/get_image_manifest_skopeo()] [WARN] CMD failed - exception: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  inspect --raw --tls-verify=false  docker://1234567890.dkr.ecr.eu-west-1.amazonaws.com/my-app-name:b076ab4, rc=1, stdout=None, stderr=b'time="2019-08-21T10:21:04Z" level=fatal msg="Error reading manifest b076ab4 in 1234567890.dkr.ecr.eu-west-1.amazonaws.com/my-app-name: unauthorized: authentication required" \n', error_code=REGISTRY_PERMISSION_DENIED
[service:catalog] 2019-08-21 10:21:04+0000 [-] Traceback (most recent call last):
[service:catalog] 2019-08-21 10:21:04+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/skopeo_wrapper.py", line 261, in get_image_manifest_skopeo
[service:catalog] 2019-08-21 10:21:04+0000 [-]     raise err
[service:catalog] 2019-08-21 10:21:04+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/skopeo_wrapper.py", line 243, in get_image_manifest_skopeo
[service:catalog] 2019-08-21 10:21:04+0000 [-]     rawmanifest = get_image_manifest_skopeo_raw(pullstring, user=user, pw=pw, verify=verify)
[service:catalog] 2019-08-21 10:21:04+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/skopeo_wrapper.py", line 226, in get_image_manifest_skopeo_raw
[service:catalog] 2019-08-21 10:21:04+0000 [-]     raise err
[service:catalog] 2019-08-21 10:21:04+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/skopeo_wrapper.py", line 224, in get_image_manifest_skopeo_raw
[service:catalog] 2019-08-21 10:21:04+0000 [-]     raise err
[service:catalog] 2019-08-21 10:21:04+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/skopeo_wrapper.py", line 219, in get_image_manifest_skopeo_raw
[service:catalog] 2019-08-21 10:21:04+0000 [-]     raise err
[service:catalog] 2019-08-21 10:21:04+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/skopeo_wrapper.py", line 214, in get_image_manifest_skopeo_raw
[service:catalog] 2019-08-21 10:21:04+0000 [-]     raise SkopeoError(cmd=cmd, rc=rc, out=sout, err=serr)
[service:catalog] 2019-08-21 10:21:04+0000 [-] anchore_engine.clients.skopeo_wrapper.SkopeoError: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  inspect --raw --tls-verify=false  docker://1234567890.dkr.ecr.eu-west-1.amazonaws.com/my-app-name:b076ab4, rc=1, stdout=None, stderr=b'time="2019-08-21T10:21:04Z" level=fatal msg="Error reading manifest b076ab4 in 1234567890.dkr.ecr.eu-west-1.amazonaws.com/my-app-name: unauthorized: authentication required" \n', error_code=REGISTRY_PERMISSION_DENIED
[service:catalog] 2019-08-21 10:21:04+0000 [_GenericHTTPChannelProtocol,156582,10.3.27.193] [PoolThread-twisted.internet.reactor-2] [anchore_engine.clients.docker_registry/get_image_manifest()] [ERROR] could not fetch manifest/digest: Error encountered in skopeo operation. cmd=/bin/sh -c skopeo  inspect --raw --tls-verify=false  docker://1234567890.dkr.ecr.eu-west-1.amazonaws.com/my-app-name:b076ab4, rc=1, stdout=None, stderr=b'time="2019-08-21T10:21:04Z" level=fatal msg="Error reading manifest b076ab4 in 1234567890.dkr.ecr.eu-west-1.amazonaws.com/my-app-name: unauthorized: authentication required" \n', error_code=REGISTRY_PERMISSION_DENIED

```
Is there any additional config to fix the auth for skopeo or is this an issue with the controller itself ?

**Comment by brennoo** [comment]
I think I found the issue: it is needed to add the ECR registry within admission-controller account

`anchore-cli --as-account admission-controller registry add 1234567890.dkr.ecr.eu-west-1.amazonaws.com awsauto awsauto --registry-type=awsecr`

even though the registry added as admin was showing when I ran `anchore-cli --as-account admission-controller registry list` it was needed to add it again within admission controller account

**Comment by zhill** [comment]
Hi @brennoo, from that log snippet it looks like your anchore engine installation is not configured with credentials to be able to pull the images for analysis. You need to add credentials via the `anchore-cli registry add` command to enable that access and things should work.

**Comment by zhill** [comment]
Oh, looks like you just beat me to it. We've fixed some issues in the CLI that should make the registry listing show the correct listing when you are admin using the --as-account flag (https://github.com/anchore/anchore-cli/issues/33)
