### ISSUE TITLE
In generated client (based on openapi spec) the ImagesApi.AddImage() method not work.

### ISSUE THREAD

**Issue by pbalogh-sa** [anchore/anchore-engine#283]
**This is a BUG REPORT**

**Version of Anchore Engine and Anchore CLI if applicable**:
anchore-engine: v.0.5.0
swagger Anchore Engine API Server version: 0.1.12
openapi: 3.0.1
 
**What happened**:
I tried the new kubernetes-admission-controller image I built using the generated API client.
https://github.com/anchore/kubernetes-admission-controller/pull/14

When an image hasn't analyzed yet by anchore-engine the controller adds it to analyze, but AddImage() isn't work.

**What did you expect to happen**:
The generated ImagesApi.AddImage() method should work properly.

**Any relevant log output from /var/log/anchore**:
catalog log:
```
[service:catalog] 2019-10-16 09:12:44+0000 [-] Traceback (most recent call last):
[service:catalog] 2019-10-16 09:12:44+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/catalog/catalog_impl.py", line 282, in image
[service:catalog] 2019-10-16 09:12:44+0000 [-]     raise err
[service:catalog] 2019-10-16 09:12:44+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/catalog/catalog_impl.py", line 280, in image
[service:catalog] 2019-10-16 09:12:44+0000 [-]     raise Exception("image data not found in DB")
[service:catalog] 2019-10-16 09:12:44+0000 [-] Exception: image data not found in DB
[service:catalog] 2019-10-16 09:12:44+0000 [_GenericHTTPChannelProtocol,88747,10.12.2.213] [PoolThread-twisted.internet.reactor-2] [anchore_engine.services.catalog.catalog_impl/image()] [ERROR] Error processing image request
[service:catalog] 2019-10-16 09:12:44+0000 [-] "10.12.2.213" - - [16/Oct/2019:09:12:44 +0000] "GET /v1/images?tag=poke%2Fkafka-operator&registry_lookup=False HTTP/1.1" 404 106 "-" "python-requests/2.20.0"
[service:catalog] 2019-10-16 09:12:51+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:12:50 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:12:53+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:12:52 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:13:01+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:13:00 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:13:03+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:13:02 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:13:11+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:13:10 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:13:13+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:13:12 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:13:21+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:13:20 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:13:23+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:13:22 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:13:31+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:13:30 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:13:33+0000 [-] "10.12.1.1" - - [16/Oct/2019:09:13:32 +0000] "GET /health HTTP/1.1" 200 - "-" "kube-probe/1.12+"
[service:catalog] 2019-10-16 09:13:35+0000 [-] Traceback (most recent call last):
[service:catalog] 2019-10-16 09:13:35+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/catalog/catalog_impl.py", line 282, in image
[service:catalog] 2019-10-16 09:13:35+0000 [-]     raise err
[service:catalog] 2019-10-16 09:13:35+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/catalog/catalog_impl.py", line 280, in image
[service:catalog] 2019-10-16 09:13:35+0000 [-]     raise Exception("image data not found in DB")
[service:catalog] 2019-10-16 09:13:35+0000 [-] Exception: image data not found in DB
[service:catalog] 2019-10-16 09:13:35+0000 [_GenericHTTPChannelProtocol,88758,10.12.2.213] [PoolThread-twisted.internet.reactor-3] [anchore_engine.services.catalog.catalog_impl/image()] [ERROR] Error processing image request
[service:catalog] 2019-10-16 09:13:35+0000 [-] "10.12.2.213" - - [16/Oct/2019:09:13:34 +0000] "GET /v1/images?tag=poke%2Fkafka-operator&registry_lookup=False HTTP/1.1" 404 106 "-" "python-requests/2.20.0"
[service:catalog] 2019-10-16 09:13:36+0000 [-] Traceback (most recent call last):
[service:catalog] 2019-10-16 09:13:36+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/catalog/catalog_impl.py", line 282, in image
[service:catalog] 2019-10-16 09:13:36+0000 [-]     raise err
[service:catalog] 2019-10-16 09:13:36+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/catalog/catalog_impl.py", line 280, in image
[service:catalog] 2019-10-16 09:13:36+0000 [-]     raise Exception("image data not found in DB")
[service:catalog] 2019-10-16 09:13:36+0000 [-] Exception: image data not found in DB
[service:catalog] 2019-10-16 09:13:36+0000 [_GenericHTTPChannelProtocol,88759,10.12.2.213] [PoolThread-twisted.internet.reactor-4] [anchore_engine.services.catalog.catalog_impl/image()] [ERROR] Error processing image request
[service:catalog] 2019-10-16 09:13:36+0000 [-] "10.12.2.213" - - [16/Oct/2019:09:13:36 +0000] "GET /v1/images?tag=poke%2Fkafka-operator&registry_lookup=False HTTP/1.1" 404 106 "-" "python-requests/2.20.0"
```

**What docker images are you using**:
docker.io/anchore/anchore-engine:v0.5.0

**How to reproduce the issue**:
Use the generated client ImagesApi.AddImage() method

**Anything else we need to know**:
I tried it with:
https://github.com/anchore/kubernetes-admission-controller/pull/14
The admission-controller log:
```
I1016 09:04:10.696348       1 main.go:341] Image is not analyzed
I1016 09:04:10.696485       1 main.go:294] Requesting analysis of image image=poke/kafka-operator
I1016 09:04:10.696534       1 main.go:322] Performing passive validation. Will request image analysis and always allow admission
E1016 09:04:10.849970       1 main.go:327] Error from analysis request err=400 Bad Request
I1016 09:04:10.850062       1 main.go:317] Returning status=&AdmissionResponse{UID:b04ea963-14f4-433b-955f-89253b2d5871,Allowed:false,Result:&k8s_io_apimachinery_pkg_apis_meta_v1.Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,},Status:Failure,Message:Image poke/kafka-operator is not analyzed.,Reason:,Details:nil,Code:0,},Patch:nil,PatchType:nil,AuditAnnotations:map[string]string{},}
```

**Comment by zhill** [comment]
Can you confirm if this is also occurring in v0.5.1? It may depend on which form of the POST body is used by the generated code: "source" or combination of "tag" & "digest" fields

**Comment by zhill** [comment]
Can you show exactly what the call looks like? Or is it just what's in that PR already?

**Comment by pbalogh-sa** [comment]
https://github.com/banzaicloud/kubernetes-admission-controller/blob/5d59763ab9f1b10deb6fe8b0dab77807f0a6bd6c/cmd/kubernetes-admission-controller/main.go#L385-L411

**Comment by zhill** [comment]
Was this also failing with the old client version or only after the update? Trying to narrow it down to either a change in the client or a change in v0.5.1.

This works fine against my v0.5.1 test system, and it seems to have the same parameters as your example:
```
curl -u admin:foobar -H "Content-Type: application/json" -d'{"tag": "library/centos", "created_at": "2019-10-10T12:00:00Z", "annotations": {"source": "test1"}}' -X POST http://localhost:8228/v1/images?autosubscribe=False
```
Can you show the exact request body generated by the client and the error response from the service so we can see where that 400 is coming from?

**Comment by pbalogh-sa** [comment]
I printed the whole request and I saw a strange thing:
The ImageAnalysisRequest I used:
```
	req := anchore.ImageAnalysisRequest{
		Tag:         imageRef,
		Annotations: annotations,
		CreatedAt:   time.Now().UTC().Round(time.Second),
	}
```
When I printed it I saw why the AddImage not worked properely.
```
I1023 12:07:17.773213       1 main.go:400] ----- Print ImageAnalysisRequest in main: {  poke/kafka-operator 0001-01-01 00:00:00 +0000 UTC  map[requestor:anchore-admission-controller] {{ } {  0001-01-01 00:00:00 +0000 UTC } {}}}
I1023 12:07:17.773333       1 main.go:401] ----- Print marshalled ImageAnalysisRequest in main: {"tag":"poke/kafka-operator","created_at":"0001-01-01T00:00:00Z","annotations":{"requestor":"anchore-admission-controller"},"source":{"tag":{"pullstring":""},"digest":{"pullstring":"","tag":"","creation_timestamp_override":"0001-01-01T00:00:00Z"},"archive":{"digest":""}}}
```
Somehow the Source initialized with zero instead of leaved it from struct.

**Comment by pbalogh-sa** [comment]
The generated ImageAnalysisRequest struct is:
```
// ImageAnalysisRequest A request to add an image to be watched and analyzed by the engine. Optionally include the dockerfile content. Either source, digest or tag must be present.
type ImageAnalysisRequest struct {
	// Base64 encoded content of the dockerfile for the image, if available. Deprecated in favor of the 'source' field.
	Dockerfile string `json:"dockerfile,omitempty"`
	// A digest string for an image, maybe a pull string or just a digest. e.g. nginx@sha256:123 or sha256:abc123. If a pull string, it must have same regisry/repo as the tag field. Deprecated in favor of the 'source' field
	Digest string `json:"digest,omitempty"`
	// Full pullable tag reference for image. e.g. docker.io/nginx:latest. Deprecated in favor of the 'source' field
	Tag string `json:"tag,omitempty"`
	// Optional override of the image creation time, only honored when both tag and digest are also supplied  e.g. 2018-10-17T18:14:00Z. Deprecated in favor of the 'source' field
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Optional. The type of image this is adding, defaults to \"docker\". This can be ommitted until multiple image types are supported.
	ImageType string `json:"image_type,omitempty"`
	// Annotations to be associated with the added image in key/value form
	Annotations map[string]interface{} `json:"annotations,omitempty"`
	Source ImageSource `json:"source,omitempty"`
}
```

Maybe if the Source was a pointer of ImageSource struct instead of ImageSource struct it would solve the problem.

**Comment by pbalogh-sa** [comment]
I changed the ImageAnalysisRequest definition using `Source *ImageSource `json:"source,omitempty"``  and it works now. 
```
I1024 07:48:50.081453       1 main.go:400] ----- Print ImageAnalysisRequest in main: {  redis:5.0 2019-10-24 07:48:50 +0000 UTC  map[requestor:anchore-admission-controller] <nil>}
I1024 07:48:50.081505       1 main.go:401] ----- Print marshalled ImageAnalysisRequest in main: {"tag":"redis:5.0","created_at":"2019-10-24T07:48:50Z","annotations":{"requestor":"anchore-admission-controller"}}
```

It should be fix in your `swagger.yaml`

**Comment by pbalogh-sa** [comment]
I'm afraid of the snippet below won't work due to an openapi-generator issue ( https://github.com/OpenAPITools/openapi-generator/issues/3159 )
```
      source:
        nullable: true
        $ref: "#/definitions/ImageSource"
```
won't work due to https://github.com/OpenAPITools/openapi-generator/issues/3159

**Comment by zhill** [comment]
Can we close this @pbalogh-sa I think it's resolved as not-an-issue here since you have the fix in the controller repo. Let me know if there are remaining issues to resolve. Thanks!

**Comment by pbalogh-sa** [comment]
Yes, you can close it @zhill .  If you want you can add the nullable flag for the mentioned parts for your `swaggar.yaml`. In this case, when the issue of `OpenApiTools` will be solved,  your API description will be already fixed.
