### ISSUE TITLE
AWS S3 IAM role requires ListAllMyBuckets IAM policy if region is not configured explicitly

### ISSUE THREAD

**Issue by frittentheke** [anchore/anchore-engine#297]
**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:

anchore-cli, version 0.5.0

Name: anchore-engine
Version: 0.5.1
Summary: Anchore Engine
Home-page: http://www.anchore.com
Author: Anchore Inc.
Author-email: dev@anchore.com

**What happened**:
I deployed the Helm Chart version 1.3.7 and configured S3 storage (https://docs.anchore.com/current/docs/engine/engine_installation/storage/object_store/s3_driver/) using the corresponding values 

      #   access_key: XXXX
      #   secret_key: YYYY

starting at https://github.com/helm/charts/blob/master/stable/anchore-engine/values.yaml#L337

The corresponding S3 bucket had a policy granting the user / access_key full access to the bucket itself:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::1234567890:user/anchore-s3-user"
            },
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::eu-central-1-anchorebucketname",
                "arn:aws:s3:::eu-central-1-anchorebucketname*"
            ]
        }
    ]
}
```

**What did you expect to happen**:

I expected the S3 client to be able to access and use the bucket.
But without also setting the "region" variable (to _eu-central-1_ in this case) I saw an _GetBucketLocation_ error. But GetBucketLocation is of course covered by the _s3:*_ action of the bucket policy.

Maybe the client is querying the location of all buckets? While to an issue per se, this cannot be allowed via a bucket policy and requires additional IAM policies to be used for the user. This should likely be avoided.

**Any relevant log output from /var/log/anchore**:

```
 anchore-engine-catalog Traceback (most recent call last):
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/subsys/object_store/drivers/s3.py", line 76, in _check_creds
 anchore-engine-catalog     self.s3_client.get_bucket_location(Bucket=self.bucket_name)
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
 anchore-engine-catalog     return self._make_api_call(operation_name, kwargs)    
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
 anchore-engine-catalog     raise error_class(parsed_response, operation_name)    
 anchore-engine-catalog botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetBucketLocation operation: Access Denied
 anchore-engine-catalog 
 anchore-engine-catalog During handling of the above exception, another exception occurred:
 anchore-engine-catalog 
 anchore-engine-catalog Traceback (most recent call last):
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/subsys/object_store/__init__.py", line 49, in init_driver
 anchore-engine-catalog     return _from_config(configuration=configuration)
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/subsys/object_store/__init__.py", line 34, in _from_config
 anchore-engine-catalog     return drv(driver_config)
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/subsys/object_store/drivers/s3.py", line 66, in __init__
 anchore-engine-catalog     self._check_creds()
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/subsys/object_store/drivers/s3.py", line 80, in _check_creds
 anchore-engine-catalog     raise BadCredentialsError(creds_dict=self.session.get_credentials().__dict__, endpoint=self.s3_client._endpoint, cause=ex)
 anchore-engine-catalog anchore_engine.subsys.object_store.exc.BadCredentialsError
 anchore-engine-catalog Traceback (most recent call last):
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/subsys/object_store/drivers/s3.py", line 76, in _check_creds
 anchore-engine-catalog     self.s3_client.get_bucket_location(Bucket=self.bucket_name)
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
 anchore-engine-catalog     return self._make_api_call(operation_name, kwargs)    
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
 anchore-engine-catalog     raise error_class(parsed_response, operation_name)    
 anchore-engine-catalog botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetBucketLocation operation: Access Denied
 anchore-engine-catalog 
 anchore-engine-catalog During handling of the above exception, another exception occurred:
 anchore-engine-catalog 
 anchore-engine-catalog Traceback (most recent call last):
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/catalog/__init__.py", line 1423, in _init_object_storage
 anchore-engine-catalog     did_init = object_store.initialize(self.configuration, manager_id=DEFAULT_OBJECT_STORE_MANAGER_ID, config_keys=[DEFAULT_OBJECT_STORE_MANAGER_ID, ALT_OBJECT_STORE_CONFIG_KEY], allow_legacy_fallback=True)
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/subsys/object_store/manager.py", line 301, in initialize
 anchore-engine-catalog     return initialize_direct(archive_config, manager_id=manager_id, check_db=check_db)
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/subsys/object_store/manager.py", line 317, in initialize_direct
 anchore-engine-catalog     manager_singleton[manager_id] = ObjectStorageManager(obj_store_config)
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/subsys/object_store/manager.py", line 43, in __init__
 anchore-engine-catalog     raise err
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/subsys/object_store/manager.py", line 34, in __init__
 anchore-engine-catalog     driver = object_store.init_driver(self.config[DRIVER_SECTION_KEY])
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/subsys/object_store/__init__.py", line 52, in init_driver
 anchore-engine-catalog     raise err
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/subsys/object_store/__init__.py", line 49, in init_driver
 anchore-engine-catalog     return _from_config(configuration=configuration)
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/subsys/object_store/__init__.py", line 34, in _from_config
 anchore-engine-catalog     return drv(driver_config)
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/subsys/object_store/drivers/s3.py", line 66, in __init__
 anchore-engine-catalog     self._check_creds()
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/subsys/object_store/drivers/s3.py", line 80, in _check_creds
 anchore-engine-catalog     raise BadCredentialsError(creds_dict=self.session.get_credentials().__dict__, endpoint=self.s3_client._endpoint, cause=ex)
 anchore-engine-catalog anchore_engine.subsys.object_store.exc.BadCredentialsError
 anchore-engine-catalog Traceback (most recent call last):
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/subsys/object_store/drivers/s3.py", line 76, in _check_creds
 anchore-engine-catalog     self.s3_client.get_bucket_location(Bucket=self.bucket_name)
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
 anchore-engine-catalog     return self._make_api_call(operation_name, kwargs)    
 anchore-engine-catalog   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
 anchore-engine-catalog     raise error_class(parsed_response, operation_name)    
 anchore-engine-catalog botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetBucketLocation operation: Access Denied

```

**What docker images are you using**:

Helm Chart in version 1.3.7

**Comment by zhill** [comment]
thanks @frittentheke. we'll take a look. there are a couple of issues in this area to address
