### ISSUE TITLE
Dockerfile parsing

### ISSUE THREAD

**Issue by JorisAndrade** [anchore/anchore-engine#3]
Hi Guys,

I think there is an error with the Dockerfile parsing when you use multiline.

```
2017-11-02 13:46:00+0000 [-] Traceback (most recent call last):
2017-11-02 13:46:00+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/policy_engine/api/controllers/synchronous_operations.py", line 227, in check_user_image_inline
2017-11-02 13:46:00+0000 [-]     eval_result = executable_bundle.execute(img_obj, tag, ExecutionContext(db_session=db, configuration={}))
2017-11-02 13:46:00+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/policy_engine/engine/policy/bundles.py", line 1074, in execute
2017-11-02 13:46:00+0000 [-]     errors, policy_decision = evaluated_policy.execute(image_obj=image_object, context=context)
2017-11-02 13:46:00+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/policy_engine/engine/policy/bundles.py", line 510, in execute
2017-11-02 13:46:00+0000 [-]     exec_context = gate_obj.prepare_context(image_obj, context)
2017-11-02 13:46:00+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/policy_engine/engine/policy/gates/dockerfile.py", line 359, in prepare_context
2017-11-02 13:46:00+0000 [-]     directive, remainder = line.split(' ', 1)
2017-11-02 13:46:00+0000 [-] ValueError: need more than 1 value to unpack
```

Sometimes there are no directive

```
RUN set -ex; \
    BUILD_DEPS="gcc libffi-dev libxml2-dev mariadb-dev musl-dev openssl-dev xmlsec-dev"; \
    apk add --no-cache --virtual .build-deps $BUILD_DEPS; \
    pip install --no-cache-dir --cert /etc/ssl/certs/ca-certificates.crt --requirement requirements.txt; \
    rm -r requirements.txt; \
    EXTRA_RUN_DEPS="$( \
        scanelf --needed --nobanner --recursive /usr/local \
            | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
            | sort -u \
            | xargs -r apk info --installed \
            | sort -u \
    )"; \
    apk add --no-cache --virtual .run-deps $EXTRA_RUN_DEPS; \
    apk del .build-deps
```

You should handle `\` here https://github.com/anchore/anchore-engine/blob/master/anchore_engine/services/policy_engine/engine/policy/gates/dockerfile.py#L358

Thanks !

**Comment by nurmi** [comment]
Good catch JorisAndrade - we’ll get on it and update this ticket when the bug has been dealt with!

thank you
dan

**Comment by JorisAndrade** [comment]
Thanks ! Is it possible to push a new image of the engine ?

You should do an automatic build of master ;)

**Comment by nurmi** [comment]
Yep!  Our plan is to get one pushed today which has this fix (and some other improvements).  wrt auto container, we agree for sure, and it is for sure part of our plan to do so moving forward!

**Comment by nurmi** [comment]
We have pushed a new version of the engine today which includes this fix  - thank you again

**Comment by JorisAndrade** [comment]
Thanks guys 👍
