### ISSUE TITLE
LoggingWrapper object has no attribute ''debug_exception''' when trying to sync feeds

### ISSUE THREAD

**Issue by rodrigc** [anchore/anchore-engine#346]
**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:
anchore-cli, version 0.6.1

** What happened? **

I have set up AnchoreE Community edition in a Kubernetes 1.15.5 cluster, using the helm chart.  I have most things up and running.About 12 hours ago, I did:

```
anchore-cli --version
anchore-cli, version 0.6.1
```

 anchore-cli  system feeds syncWARNING: This operation should not normally need to be performed except when the anchore-engine operator is certain that it is required - the operation will take a long time (hours) to complete, and there may be an impact on anchore-engine performance during the re-sync/flush.Really perform a manual feed data sync/flush? (y/N)y

12 hours later, I did:

```
anchore-cli  system feeds list

Feed                   Group                  LastSync        RecordCount
nvdv2                  nvdv2:cves             pending         0
vulnerabilities        alpine:3.10            pending         0
vulnerabilities        alpine:3.11            pending         0
vulnerabilities        alpine:3.3             pending         0
vulnerabilities        alpine:3.4             pending         0
vulnerabilities        alpine:3.5             pending         0
vulnerabilities        alpine:3.6             pending         0
vulnerabilities        alpine:3.7             pending         0
vulnerabilities        alpine:3.8             pending         0
vulnerabilities        alpine:3.9             pending         0
vulnerabilities        amzn:2                 pending         0
vulnerabilities        centos:5               pending         0
vulnerabilities        centos:6               pending         0
vulnerabilities        centos:7               pending         0
vulnerabilities        centos:8               pending         0
vulnerabilities        debian:10              pending         0
vulnerabilities        debian:11              pending         0
vulnerabilities        debian:7               pending         0
vulnerabilities        debian:8               pending         0
vulnerabilities        debian:9               pending         0
vulnerabilities        debian:unstable        pending         0
vulnerabilities        ol:5                   pending         0
vulnerabilities        ol:6                   pending         0
vulnerabilities        ol:7                   pending         0
vulnerabilities        ol:8                   pending         0
vulnerabilities        ubuntu:12.04           pending         0
vulnerabilities        ubuntu:12.10           pending         0
vulnerabilities        ubuntu:13.04           pending         0
vulnerabilities        ubuntu:14.04           pending         0
vulnerabilities        ubuntu:14.10           pending         0
vulnerabilities        ubuntu:15.04           pending         0
vulnerabilities        ubuntu:15.10           pending         0
vulnerabilities        ubuntu:16.04           pending         0
vulnerabilities        ubuntu:16.10           pending         0
vulnerabilities        ubuntu:17.04           pending         0
vulnerabilities        ubuntu:17.10           pending         0
vulnerabilities        ubuntu:18.04           pending         0
vulnerabilities        ubuntu:18.10           pending         0
vulnerabilities        ubuntu:19.04           pending         0
vulnerabilities        ubuntu:19.10           pending         0
```

I ran this command:

```
anchore-cli event list

Timestamp                          Level        Event                                  Resource                               ID
2020-03-05T16:22:37.411806Z        info         system.feeds.sync.completed            None                                   8243077a04554835bb0cda92f6a5008a
2020-03-05T16:22:37.102255Z        error        system.feeds.sync.feed_failed          nvdv2                                  be7771bfb0054bc79a0ffb8eeb8c033f
2020-03-05T16:22:36.981029Z        error        system.feeds.sync.group_failed         nvdv2/nvdv2:cves                       55dac8443bee451ba57290b241e25583
2020-03-05T16:22:36.856560Z        info         system.feeds.sync.group_started        nvdv2/nvdv2:cves                       753428a656364e0e9ff5424f1e29b043
2020-03-05T16:22:36.729406Z        info         system.feeds.sync.feed_started         nvdv2                                  5b725d81e45540aeb9f9a4cd75d5f589
```

and this:

```
anchore-cli event get 55dac8443bee451ba57290b241e25583
details:
  cause: '''LoggingWrapper'' object has no attribute ''debug_exception'''
level: error
message: Feed group sync failed
resource:
  id: nvdv2/nvdv2:cves
  type: feed_group
  user_id: admin
source:
  base_url: http://anchore-anchore-engine-policy:8087
  hostid: anchore-anchore-engine-policy-56767545df-mrghz
  request_id: null
  servicename: policy_engine
timestamp: '2020-03-05T16:22:36.981029Z'
type: system.feeds.sync.group_failed
```

**Comment by zhill** [comment]
Hi @rodrigc , can you check the policy engine log and see where this is being thrown? That will help me identify if its already fixed in master or 0.6.2 even or needs new work. Thanks!

**Comment by rodrigc** [comment]
@zhill I looked back a few hours and found this exception in the `anchore-anchore-engine-analyzer` pod:

```
[service:worker] 2020-03-05 04:48:41+0000 [-] [Thread-1666] [anchore_engine.services.analyzer/process_analyzer_job()] [INFO] image dequeued for analysis: admin : sha256:9a4d2d2edb44aa2170e2ad3604563dabaa195c5e926b1e8c6bd41c5750c6ff2f^M
[service:worker] 2020-03-05 04:48:41+0000 [-] [Thread-1666] [anchore_engine.services.analyzer/perform_analyze_nodocker()] [INFO] performing analysis on image: ['admin', 'docker.io/portworx/px-enterprise@sha256:9a4d2d2edb44aa2170e2ad3604563dabaa195c5e926b1e8c6bd41c5750c6ff2f', 'docker.io/portworx/px-enterprise:2.3.6']^M
[service:worker] 2020-03-05 04:48:41+0000 [-] [Thread-1666] [anchore_engine.clients.localanchore_standalone/get_anchorelock()] [INFO] copying new config into place: /anchore_service/analyzer_config.yaml -> /home/anchore/.anchore/conf/analyzer_config.yaml^M
[service:worker] 2020-03-05 04:48:41+0000 [-] Traceback (most recent call last):^M
[service:worker] 2020-03-05 04:48:41+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/localanchore_standalone.py", line 410, in make_staging_dirs^M
[service:worker] 2020-03-05 04:48:41+0000 [-]     os.makedirs(ret[k])^M
[service:worker] 2020-03-05 04:48:41+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/os.py", line 220, in makedirs^M
[service:worker] 2020-03-05 04:48:41+0000 [-]     mkdir(name, mode)^M
[service:worker] 2020-03-05 04:48:41+0000 [-] PermissionError: [Errno 13] Permission denied: '/analysis_scratch/0402ed78-2b0f-465e-badd-9c162f663a2a'^M
[service:worker] 2020-03-05 04:48:41+0000 [-] ^M
[service:worker] 2020-03-05 04:48:41+0000 [-] During handling of the above exception, another exception occurred:^M
[service:worker] 2020-03-05 04:48:41+0000 [-] ^M
[service:worker] 2020-03-05 04:48:41+0000 [-] Traceback (most recent call last):^M
[service:worker] 2020-03-05 04:48:41+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/localanchore_standalone.py", line 873, in analyze_image^M
[service:worker] 2020-03-05 04:48:41+0000 [-]     raise err^M
[service:worker] 2020-03-05 04:48:41+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/localanchore_standalone.py", line 871, in analyze_image^M
[service:worker] 2020-03-05 04:48:41+0000 [-]     staging_dirs = make_staging_dirs(tmprootdir, use_cache_dir=use_cache_dir)^M
[service:worker] 2020-03-05 04:48:41+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/clients/localanchore_standalone.py", line 412, in make_staging_dirs^M
[service:worker] 2020-03-05 04:48:41+0000 [-]     raise Exception("unable to prep staging directory - exception: " + str(err))^M
[service:worker] 2020-03-05 04:48:41+0000 [-] Exception: unable to prep staging directory - exception: [Errno 13] Permission denied: '/analysis_scratch/0402ed78-2b0f-465e-badd-9c162f663a2a'^M
[service:worker] 2020-03-05 04:48:41+0000 [-] ^M
[service:worker] 2020-03-05 04:48:41+0000 [-] During handling of the above exception, another exception occurred:^M
[service:worker] 2020-03-05 04:48:41+0000 [-] ^M
```

**Comment by rodrigc** [comment]
@zhill I found this in the `anchore-anchore-engine-policy` pod


```
[service:policy-engine] 2020-03-05 04:21:10+0000 [-] [Thread-11] [anchore_engine.services.policy_engine.engine.logs/error()] [ERROR] Error syncing vulnerabilities/alpine:3.10 (operation_id=c482e9dc1a124d5d91d347430d2d824d)^M
[service:policy-engine] 2020-03-05 04:21:10+0000 [-] [Thread-11] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Event: {"type": "system.feeds.sync.group_failed", "level": "error", "message": "Feed group sync failed", "details": {"cause": "'LoggingWrapper' object has no attribute 'debug_exception'"}, "timestamp": "2020-03-05T04:21:10.112922", "resource": {"user_id": "admin", "type": "feed_group", "id": "vulnerabilities/alpine:3.10"}, "source": {"request_id": null, "servicename": "policy_engine", "hostid": "anchore-anchore-engine-policy-56767545df-mrghz", "base_url": "http://anchore-anchore-engine-policy:8087"}} (operation_id=c482e9dc1a124d5d91d347430d2d824d)^M
[service:policy-engine] 2020-03-05 04:21:10+0000 [-] Traceback (most recent call last):^M
[service:policy-engine] 2020-03-05 04:21:10+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/sync.py", line 333, in sync^M
[service:policy-engine] 2020-03-05 04:21:10+0000 [-]     feed_data_repo.teardown()^M
[service:policy-engine] 2020-03-05 04:21:10+0000 [-] AttributeError: 'NoneType' object has no attribute 'teardown'^M
[service:policy-engine] 2020-03-05 04:21:10+0000 [-] [Thread-11] [anchore_engine.services.policy_engine.engine.logs/exception()] [ERROR] Could not cleanup download repo due to error^M
[service:policy-engine] 2020-03-05 04:21:10+0000 [-] [Thread-11] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Event: {"type": "system.feeds.sync.group_started", "level": "info", "message": "Feed group sync started", "details": {}, "timestamp": "2020-03-05T04:21:10.174506", "resource": {"user_id": "admin", "type": "feed_group", "id": "vulnerabilities/alpine:3.11"}, "source": {"request_id": null, "servicename": "policy_engine", "hostid": "anchore-anchore-engine-policy-56767545df-mrghz", "base_url": "http://anchore-anchore-engine-policy:8087"}} (operation_id=c482e9dc1a124d5d91d347430d2d824d)^M
[service:policy-engine] 2020-03-05 04:21:10+0000 [-] [Thread-11] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Beginning feed data fetch (feed=vulnerabilities, group=alpine:3.11, operation_id=c482e9dc1a124d5d91d347430d2d824d)^M
[service:policy-engine] 2020-03-05 04:21:10+0000 [-] [Thread-11] [anchore_engine.services.policy_engine.engine.logs/error()] [ERROR] Error syncing vulnerabilities/alpine:3.11 (operation_id=c482e9dc1a124d5d91d347430d2d824d)^M
[service:policy-engine] 2020-03-05 04:21:10+0000 [-] [Thread-11] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Event: {"type": "system.feeds.sync.group_failed", "level": "error", "message": "Feed group sync failed", "details": {"cause": "'LoggingWrapper' object has no attribute 'debug_exception'"}, "timestamp": "2020-03-05T04:21:10.235941", "resource": {"user_id": "admin", "type": "feed_group", "id": "vulnerabilities/alpine:3.11"}, "source": {"request_id": null, "servicename": "policy_engine", "hostid": "anchore-anchore-engine-policy-56767545df-mrghz", "base_url": "http://anchore-anchore-engine-policy:8087"}} (operation_id=c482e9dc1a124d5d91d347430d2d824d)^M
[service:policy-engine] 2020-03-05 04:21:10+0000 [-] Traceback (most recent call last):^M
[service:policy-engine] 2020-03-05 04:21:10+0000 [-]   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/sync.py", line 333, in sync^M
[service:policy-engine] 2020-03-05 04:21:10+0000 [-]     feed_data_repo.teardown()^M
[service:policy-engine] 2020-03-05 04:21:10+0000 [-] AttributeError: 'NoneType' object has no attribute 'teardown'^M
```
[service:policy-engine] 2020-03-05 04:21:08+0000 [-] [Thread-11] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Initialized feed to sync: nvdv2 (operation_id=c482e9dc1a124d5d91d347430d2d824d)^M
[service:policy-engine] 2020-03-05 04:21:09+0000 [-] [Thread-11] [anchore_engine.clients.services.internal/dispatch()] [ERROR] Failed client call to service catalog for url: http://anchore-anchore-engine-catalog:8082/v1/events. Response: {'httpcode': 500, 'anchore_error_raw': "HTTPConnectionPool(host='anchore-anchore-engine-catalog', port=8082): Max retries exceeded with url: /v1/events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f26baa2ee80>: Failed to establish a new connection: [Errno 111] Connection refused',))", 'anchore_error_json': {}}^M
[service:policy-engine] 2020-03-05 04:21:09+0000 [-] [Thread-11] [anchore_engine.services.policy_engine.engine.logs/warn()] [WARN] Error adding feed start event: failed post url=http://anchore-anchore-engine-catalog:8082/v1/events^M
[service:policy-engine] 2020-03-05 04:21:09+0000 [-] [Thread-11] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Event: {"type": "system.feeds.sync.feed_started", "level": "info", "message": "Feed sync started", "details": {}, "timestamp": "2020-03-05T04:21:08.019756", "resource": {"user_id": "admin", "type": "feed", "id": "vulnerabilities"}, "source": {"request_id": null, "servicename": "policy_engine", "hostid": "anchore-anchore-engine-policy-56767545df-mrghz", "base_url": "http://anchore-anchore-engine-policy:8087"}} (operation_id=c482e9dc1a124d5d91d347430d2d824d)^M
[service:policy-engine] 2020-03-05 04:21:10+0000 [-] [Thread-11] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Event: {"type": "system.feeds.sync.group_started", "level": "info", "message": "Feed group sync started", "details": {}, "timestamp": "2020-03-05T04:21:09.030841", "resource": {"user_id": "admin", "type": "feed_group", "id": "vulnerabilities/alpine:3.10"}, "source": {"request_id": null, "servicename": "policy_engine", "hostid": "anchore-anchore-engine-policy-56767545df-mrghz", "base_url": "http://anchore-anchore-engine-policy:8087"}} (operation_id=c482e9dc1a124d5d91d347430d2d824d)^M
[service:policy-engine] 2020-03-05 04:21:10+0000 [-] [Thread-11] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Beginning feed data fetch (feed=vulnerabilities, group=alpine:3.10, operation_id=c482e9dc1a124d5d91d347430d2d824d)^M
[service:policy-engine] 2020-03-05 04:21:10+0000 [-] [Thread-11] [anchore_engine.services.policy_engine.engine.logs/error()] [ERROR] Error syncing vulnerabilities/alpine:3.10 (operation_id=c482e9dc1a124d5d91d347430d2d824d)^M
[service:policy-engine] 2020-03-05 04:21:10+0000 [-] [Thread-11] [anchore_engine.services.policy_engine.engine.logs/info()] [INFO] Event: {"type": "system.feeds.sync.group_failed", "level": "error", "message": "Feed group sync failed", "details": {"cause": "'LoggingWrapper' object has no attribute 'debug_exception'"}, "timestamp": "2020-03-05T04:21:10.112922", "resource": {"user_id": "admin", "type": "feed_group", "id": "vulnerabilities/alpine:3.10"}, "source": {"request_id": null, "servicename": "policy_engine", "hostid": "anchore-anchore-engine-policy-56767545df-mrghz", "base_url": "http://anchore-anchore-engine-policy:8087"}} (operation_id=c482e9dc1a124d5d91d347430d2d824d)^M
```

**Comment by zhill** [comment]
Thanks, that helps. The 'teardown()' exception is just logging noise, not the cause of the issue, but I think I've identified the issue based on that trace. This looks like a problem in the error path encountered when the engine cannot connect to the feed service to pull data or cannot prepare the local disk location to spool the downloaded feed data for processing.

The possible culprits are:
https://github.com/anchore/anchore-engine/blob/master/anchore_engine/services/policy_engine/engine/feeds/download.py#L284
and 
https://github.com/anchore/anchore-engine/blob/master/anchore_engine/services/policy_engine/engine/feeds/download.py#L323

I'll keep this open to track the logging error, but that isn't the cause of the sync failure.

Are syncs always failing or only sometimes?

**Comment by rodrigc** [comment]
So the root cause of my problem was that in the `anchore-anchore-engine-policy` the permissions on my `/analysis_scratch/` directory was `755` so the anchore user could not create directories in there.  That seems to have fixed some things, and it looks like the feeds are now updating.

However, you should definitely fix the `debug_exception` problem as shown by `anchore-cli event get` , since that makes debugging things more difficult.....

**Comment by rodrigc** [comment]
Before I changed the permissions on `/analysis_scratch`, the syncing of feeds was always failing.

**Comment by zhill** [comment]
Yes, for sure. This will track those two locations I mentioned above. Did you deploy with our helm chart or your own deploy mechanism? The scratch location should always be writable in our deployment templates.

**Comment by rodrigc** [comment]
I used your helm chart, but I deviated a bit.  Instead of using `emptyDir{}` for the `/analysis_scratch` directory,
in the helm chart I specified a PVC which I had previously allocated. 

So when my pod comes up, I have:

```
/dev/pxd/pxd657858724312784443 on /analysis_scratch type ext4 (rw,relatime,seclabel,discard,data=ordered)
```

`/dev/pxd` is coming from Portworx. (I work for Portworx, so I use Portworx PVC's quite heavily)

**Comment by rodrigc** [comment]
Now it looks like my feeds are updating:

```
Feed                   Group                  LastSync                          RecordCount
nvdv2                  nvdv2:cves             pending                           0
vulnerabilities        alpine:3.10            2020-03-05T19:07:53.977506        1725
vulnerabilities        alpine:3.11            2020-03-05T19:09:20.404642        1904
vulnerabilities        alpine:3.3             2020-03-05T19:09:53.627914        457
vulnerabilities        alpine:3.4             2020-03-05T19:10:03.767240        681
vulnerabilities        alpine:3.5             2020-03-05T19:10:15.096322        875
vulnerabilities        alpine:3.6             2020-03-05T19:10:30.277965        1051
vulnerabilities        alpine:3.7             2020-03-05T19:10:46.327806        1395
vulnerabilities        alpine:3.8             2020-03-05T19:11:08.170643        1486
vulnerabilities        alpine:3.9             2020-03-05T19:11:30.618201        1558
vulnerabilities        amzn:2                 2020-03-05T19:11:55.790085        310
vulnerabilities        centos:5               2020-03-05T19:12:15.429872        1347
vulnerabilities        centos:6               2020-03-05T19:13:07.507636        1385
vulnerabilities        centos:7               2020-03-05T19:15:21.917081        993
vulnerabilities        centos:8               2020-03-05T19:16:32.714131        193
vulnerabilities        debian:10              2020-03-05T19:17:01.102929        22300
vulnerabilities        debian:11              pending                           13500
vulnerabilities        debian:7               pending                           0
vulnerabilities        debian:8               pending                           0
vulnerabilities        debian:9               pending                           0
vulnerabilities        debian:unstable        pending                           0
vulnerabilities        ol:5                   pending                           0
vulnerabilities        ol:6                   pending                           0
vulnerabilities        ol:7                   pending                           0
vulnerabilities        ol:8                   pending                           0
vulnerabilities        ubuntu:12.04           pending                           0
vulnerabilities        ubuntu:12.10           pending                           0
vulnerabilities        ubuntu:13.04           pending                           0
vulnerabilities        ubuntu:14.04           pending                           0
vulnerabilities        ubuntu:14.10           pending                           0
vulnerabilities        ubuntu:15.04           pending                           0
vulnerabilities        ubuntu:15.10           pending                           0
vulnerabilities        ubuntu:16.04           pending                           0
vulnerabilities        ubuntu:16.10           pending                           0
vulnerabilities        ubuntu:17.04           pending                           0
vulnerabilities        ubuntu:17.10           pending                           0
vulnerabilities        ubuntu:18.04           pending                           0
vulnerabilities        ubuntu:18.10           pending                           0
vulnerabilities        ubuntu:19.04           pending                           0
vulnerabilities        ubuntu:19.10           pending                           0
```
