### ISSUE TITLE
Improve logging/messaging when feeds are experiencing issues

### ISSUE THREAD

**Issue by robertp** [anchore/anchore-engine#454]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): Feature request/enhancement

When attempting to sync feeds, it seemed to be taking a long time.  System status looked ok (note this is local, using Docker Compose):

```shell
$ docker-compose exec api anchore-cli system status

Service catalog (anchore-quickstart, http://catalog:8228): up
Service analyzer (anchore-quickstart, http://analyzer:8228): up
Service reports (anchore-quickstart, http://reports:8228): up
Service rbac_authorizer (anchore-quickstart, http://rbac-authorizer:8228): up
Service policy_engine (anchore-quickstart, http://policy-engine:8228): up
Service simplequeue (anchore-quickstart, http://queue:8228): up
Service notifications (anchore-quickstart, http://notifications:8228): up
Service apiext (anchore-quickstart, http://api:8228): up
Service rbac_manager (anchore-quickstart, http://rbac-manager:8228): up
Engine DB Version: 0.0.13
Engine Code Version: 2.3.0
```
Then, when looking at the event list:

```shell
$ docker-compose exec api anchore-cli event list

Timestamp                          Level        Event                            Resource        ID                                      
2020-05-14T04:41:46.416346Z        info         system.feeds.sync.started        None            55bc1d33cb2b49f594064c24ab42c9f3        
2020-05-13T22:41:46.160518Z        error        system.feeds.sync.failed         None            d2eccc826ee94f56ab54d5651857f77c        
2020-05-13T22:38:45.537610Z        info         system.feeds.sync.started        None            02bfab13eee24f42960b9d2843a6cabf        
2020-05-13T22:35:10.061276Z        error        system.feeds.sync.failed         None            9376543099fd48a1853fb5bba33d6aad        
2020-05-13T22:32:09.234924Z        info         system.feeds.sync.started        None            af07954278d84648ba9c03d060483fe1 
```
Drilling down:

```shell
$  docker-compose exec api anchore-cli event get d2eccc826ee94f56ab54d5651857f77c

details:
  cause: 'Feed list operation failed. Msg: None. Response: None'
  sync_feed_types:
  - vulnerabilities
  - nvdv2
  - github
level: error
message: Feeds sync task failed
resource:
  id: null
  type: feeds
  user_id: admin
source:
  base_url: http://policy-engine:8228
  hostid: anchore-quickstart
  request_id: null
  servicename: policy_engine
timestamp: '2020-05-13T22:41:46.160518Z'
type: system.feeds.sync.failed
```
So it was clear there were issues, but it wasn't clear really what was wrong.

Looking at logs:

```shell
$ docker-compose logs policy-engine

...
36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:38:45+0000 [-] [Thread-8] [anchore_engine.services.policy_engine/handle_feed_sync_trigger()] [INFO] Feed Sync task creator activated
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:38:45+0000 [-] [Thread-8] [anchore_engine.services.policy_engine/handle_feed_sync_trigger()] [INFO] Feed Sync Trigger done, waiting for next cycle.
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:38:45+0000 [-] [Thread-8] [anchore_engine.services.policy_engine/handle_feed_sync_trigger()] [INFO] Feed Sync task creator complete
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:39:13+0000 [-] "127.0.0.1" - - [14/May/2020:04:39:13 +0000] "GET /health HTTP/1.1" 200 5 "-" "curl/7.61.1"
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:39:43+0000 [-] "127.0.0.1" - - [14/May/2020:04:39:43 +0000] "GET /health HTTP/1.1" 200 5 "-" "curl/7.61.1"
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:40:14+0000 [-] "127.0.0.1" - - [14/May/2020:04:40:13 +0000] "GET /health HTTP/1.1" 200 5 "-" "curl/7.61.1"
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:40:46+0000 [-] "172.22.0.5" - - [14/May/2020:04:40:46 +0000] "GET /v1/feeds?include_counts=True HTTP/1.1" 200 3 "-" "python-requests/2.23.0"
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:41:14+0000 [-] "127.0.0.1" - - [14/May/2020:04:41:14 +0000] "GET /health HTTP/1.1" 200 5 "-" "curl/7.61.1"
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:41:45+0000 [-] "127.0.0.1" - - [14/May/2020:04:41:44 +0000] "GET /health HTTP/1.1" 200 5 "-" "curl/7.61.1"
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:41:46+0000 [-] [Thread-9] [anchore_engine.services.policy_engine/handle_feed_sync()] [INFO] Feed sync task executor activated
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:41:46+0000 [-] [Thread-21793] [anchore_engine.services.policy_engine/do_feed_sync()] [INFO] FIRING: feed syncer
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:41:46+0000 [-] [Thread-21793] [anchore_engine.services.policy_engine/do_feed_sync()] [INFO] Syncing configured feeds: ['vulnerabilities', 'nvdv2', 'github']
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:41:46+0000 [-] [Thread-21794] [anchore_engine.services.policy_engine.engine.tasks/execute()] [INFO] Starting feed sync. (operation_id=61686dce690b416ebfa17413c9594d75)
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:41:46+0000 [-] [Thread-21794] [anchore_engine.services.policy_engine.engine.feeds.feeds/notify_event()] [INFO] Event: {"type": "system.feeds.sync.started", "level": "info", "message": "Feeds sync task started", "details": {"sync_feed_types": ["vulnerabilities", "nvdv2", "github"]}, "timestamp": "2020-05-14T04:41:46.416346", "resource": {"user_id": "admin", "type": "feeds", "id": null}, "source": {"request_id": null, "servicename": "policy_engine", "hostid": "anchore-quickstart", "base_url": "http://policy-engine:8228"}} (operation_id=61686dce690b416ebfa17413c9594d75)
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:41:46+0000 [-] [Thread-21794] [anchore_engine.services.policy_engine.engine.feeds.sync/sync()] [INFO] Performing sync of feeds: ['vulnerabilities', 'nvdv2', 'github'] (operation_id=61686dce690b416ebfa17413c9594d75)
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:41:46+0000 [-] [Thread-21794] [anchore_engine.services.policy_engine.engine.feeds.sync/sync_metadata()] [INFO] Syncing feed and group metadata from upstream source (operation_id=61686dce690b416ebfa17413c9594d75)
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:42:15+0000 [-] "127.0.0.1" - - [14/May/2020:04:42:15 +0000] "GET /health HTTP/1.1" 200 5 "-" "curl/7.61.1"
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:42:45+0000 [-] "127.0.0.1" - - [14/May/2020:04:42:45 +0000] "GET /health HTTP/1.1" 200 5 "-" "curl/7.61.1"
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:43:16+0000 [-] "127.0.0.1" - - [14/May/2020:04:43:15 +0000] "GET /health HTTP/1.1" 200 5 "-" "curl/7.61.1"
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:43:46+0000 [-] "127.0.0.1" - - [14/May/2020:04:43:46 +0000] "GET /health HTTP/1.1" 200 5 "-" "curl/7.61.1"
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:44:17+0000 [-] "127.0.0.1" - - [14/May/2020:04:44:16 +0000] "GET /health HTTP/1.1" 200 5 "-" "curl/7.61.1"
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:44:47+0000 [-] Traceback (most recent call last):
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:44:47+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/client.py", line 72, in list_feeds
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:44:47+0000 [-]     'Feed list operation failed. Msg: {}. Response: {}'.format(record.get('err_msg'), record.get('text')))
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:44:47+0000 [-] Exception: Feed list operation failed. Msg: None. Response: None
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:44:47+0000 [-] [Thread-21794] [anchore_engine.services.policy_engine.engine.feeds.client/list_feeds()] [ERROR] Error executing feed listing: Feed list operation failed. Msg: None. Response: None
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:44:47+0000 [-] [Thread-21794] [anchore_engine.services.policy_engine.engine.feeds.sync/sync_metadata()] [ERROR] Rolling back feed metadata update due to error: Feed list operation failed. Msg: None. Response: None (operation_id=61686dce690b416ebfa17413c9594d75)
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:44:47+0000 [-] Traceback (most recent call last):
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:44:47+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/tasks.py", line 196, in execute
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:44:47+0000 [-]     updated_dict = DataFeeds.sync(to_sync=self.feeds, full_flush=self.full_flush, catalog_client=catalog_client, operation_id=self.uuid)
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:44:47+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/sync.py", line 237, in sync
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:44:47+0000 [-]     updated, failed = DataFeeds.sync_metadata(feed_client=feed_client, to_sync=to_sync, operation_id=operation_id)
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:44:47+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/sync.py", line 102, in sync_metadata
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:44:47+0000 [-]     source_resp = feed_client.list_feeds()
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:44:47+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/client.py", line 75, in list_feeds
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:44:47+0000 [-]     raise e
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:44:47+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/client.py", line 72, in list_feeds
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:44:47+0000 [-]     'Feed list operation failed. Msg: {}. Response: {}'.format(record.get('err_msg'), record.get('text')))
[36mpolicy-engine_1    |[0m [service:enterprise-policy-engine] 2020-05-14 04:44:47+0000 [-] Exception: Feed list operation failed. Msg: None. Response: None
...
```
**Version of Anchore Engine and Anchore CLI if applicable**: CLI 0.7.1

**What did you expect to happen**: In the `event get` API call, it would be preferable to list more information about an erroneous condition. 

**What docker images are you using**: Enterprise v2.3.0 images

**Comment by nwl** [comment]
Related: https://github.com/anchore/enterprise/issues/235

**Comment by nightfurys** [comment]
@nwl, I think this is more a case of clarity in the anchore-engine event. The issue actually occurred against ancho.re, so any open source client could have hit it

**Comment by nwl** [comment]
Understood. Comment linkage was to ensure that any errors should be surfaced in all parts of the API (and higher level services).

**Comment by zhill** [comment]
In this case the error would be 'Got empty/error response from feed service', for example.

Specifically, can add the HTTP response code, and any error message in the response from the service into the event emitted. Maybe also a request duration (e.g. took 30s).

**Comment by cramakan** [comment]
i am also facing same  issue getting below error

[service:policy-engine] 2020-08-13 04:19:10+0000 [-] Traceback (most recent call last):
[service:policy-engine] 2020-08-13 04:19:10+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/client.py", line 72, in list_feeds
[service:policy-engine] 2020-08-13 04:19:10+0000 [-]     'Feed list operation failed. Msg: {}. Response: {}'.format(record.get('err_msg'), record.get('text')))
[service:policy-engine] 2020-08-13 04:19:10+0000 [-] Exception: Feed list operation failed. Msg: None. Response: None
[service:policy-engine] 2020-08-13 04:19:10+0000 [-] [Thread-43249] [anchore_engine.services.policy_engine.engine.feeds.client/list_feeds()] [ERROR] Error executing feed listing: Feed list operation failed. Msg: None. Response: None
[service:policy-engine] 2020-08-13 04:19:10+0000 [-] [Thread-43249] [anchore_engine.services.policy_engine.engine.feeds.sync/sync_metadata()] [ERROR] Rolling back feed metadata update due to error: Feed list operation failed. Msg: None. Response: None (operation_id=bc36a9c02c394b409c35ee2513cdd464)
[service:policy-engine] 2020-08-13 04:19:10+0000 [-] Traceback (most recent call last):
[service:policy-engine] 2020-08-13 04:19:10+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/tasks.py", line 196, in execute
[service:policy-engine] 2020-08-13 04:19:10+0000 [-]     updated_dict = DataFeeds.sync(to_sync=self.feeds, full_flush=self.full_flush, catalog_client=catalog_client, operation_id=self.uuid)
[service:policy-engine] 2020-08-13 04:19:10+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/sync.py", line 240, in sync
[service:policy-engine] 2020-08-13 04:19:10+0000 [-]     updated, failed = DataFeeds.sync_metadata(feed_client=feed_client, to_sync=to_sync, operation_id=operation_id)
[service:policy-engine] 2020-08-13 04:19:10+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/sync.py", line 105, in sync_metadata
[service:policy-engine] 2020-08-13 04:19:10+0000 [-]     source_resp = feed_client.list_feeds()
[service:policy-engine] 2020-08-13 04:19:10+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/client.py", line 75, in list_feeds
[service:policy-engine] 2020-08-13 04:19:10+0000 [-]     raise e
[service:policy-engine] 2020-08-13 04:19:10+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/client.py", line 72, in list_feeds
[service:policy-engine] 2020-08-13 04:19:10+0000 [-]     'Feed list operation failed. Msg: {}. Response: {}'.format(record.get('err_msg'), record.get('text')))
[service:policy-engine] 2020-08-13 04:19:10+0000 [-] Exception: Feed list operation failed. Msg: None. Response: None

**Comment by sairose** [comment]
I am also facing same issue, any solutions? 
![IMG-20201112-WA0018](https://user-images.githubusercontent.com/31003896/99259171-a028a100-283f-11eb-83cf-35c1b07bedda.jpeg)
