### ISSUE TITLE
Unable to sync feed

### ISSUE THREAD

**Issue by navzen2000** [anchore/anchore-engine#488]
**Is this a request for help?**:

Yes

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):

BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:
anchore-engine:v0.7.2 

**What happened**:
Feed Sync did not get the vuln data
/scratch/docker/docker-compose exec api anchore-cli system feeds sync

WARNING: This operation should not normally need to be performed except when the anchore-engine operator is certain that it is required - the operation will take a long time (hours) to complete, and there may be an impact on anchore-engine performance during the re-sync/flush.

Really perform a manual feed data sync/flush? (y/N)y

**What did you expect to happen**:
/scratch/docker/docker-compose exec api anchore-cli system feeds list

does not show any data

**Any relevant log output from /var/log/anchore**:
2020-06-15 12:25:05+0000 [-] [Thread-2818] [anchore_engine.services.policy_engine.engine.feeds.sync/sync_metadata()] [INFO] Syncing feed and group metadata from upstream source (operation_id=499401e7b8744b9ab14feb5eac572340)
2020-06-15 12:25:26+0000 [-] "127.0.0.1" - - [15/Jun/2020:12:25:26 +0000] "GET /health HTTP/1.1" 200 5 "-" "curl/7.61.1"
2020-06-15 12:25:32+0000 [-] Traceback (most recent call last):
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/client.py", line 72, in list_feeds
2020-06-15 12:25:32+0000 [-]     'Feed list operation failed. Msg: {}. Response: {}'.format(record.get('err_msg'), record.get('text')))
2020-06-15 12:25:32+0000 [-] Exception: Feed list operation failed. Msg: None. Response: None
2020-06-15 12:25:32+0000 [-] [Thread-2818] [anchore_engine.services.policy_engine.engine.feeds.client/list_feeds()] [ERROR] Error executing feed listing: Feed list operation failed. Msg: None. Response: None
2020-06-15 12:25:32+0000 [-] [Thread-2818] [anchore_engine.services.policy_engine.engine.feeds.sync/sync_metadata()] [ERROR] Rolling back feed metadata update due to error: Feed list operation failed. Msg: None. Response: None (operation_id=499401e7b8744b9ab14feb5eac572340)
2020-06-15 12:25:32+0000 [-] Traceback (most recent call last):
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/tasks.py", line 196, in execute
2020-06-15 12:25:32+0000 [-]     updated_dict = DataFeeds.sync(to_sync=self.feeds, full_flush=self.full_flush, catalog_client=catalog_client, operation_id=self.uuid)
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/sync.py", line 240, in sync
2020-06-15 12:25:32+0000 [-]     updated, failed = DataFeeds.sync_metadata(feed_client=feed_client, to_sync=to_sync, operation_id=operation_id)
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/sync.py", line 105, in sync_metadata
2020-06-15 12:25:32+0000 [-]     source_resp = feed_client.list_feeds()
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/client.py", line 75, in list_feeds
2020-06-15 12:25:32+0000 [-]     raise e
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/client.py", line 72, in list_feeds
2020-06-15 12:25:32+0000 [-]     'Feed list operation failed. Msg: {}. Response: {}'.format(record.get('err_msg'), record.get('text')))
2020-06-15 12:25:32+0000 [-] Exception: Feed list operation failed. Msg: None. Response: None
2020-06-15 12:25:32+0000 [-] [Thread-2818] [anchore_engine.services.policy_engine.engine.tasks/execute()] [ERROR] Failure refreshing and syncing feeds. (operation_id=499401e7b8744b9ab14feb5eac572340)
2020-06-15 12:25:32+0000 [-] [Thread-2818] [anchore_engine.services.policy_engine.engine.feeds.feeds/notify_event()] [INFO] Event: {"type": "system.feeds.sync.failed", "level": "error", "message": "Feeds sync task failed", "details": {"cause": "Feed list operation failed. Msg: None. Response: None", "sync_feed_types": ["vulnerabilities", "nvdv2", "github"]}, "timestamp": "2020-06-15T12:25:32.491896", "resource": {"user_id": "admin", "type": "feeds", "id": null}, "source": {"request_id": null, "servicename": "policy_engine", "hostid": "anchore-quickstart", "base_url": "http://policy-engine:8228"}} (operation_id=499401e7b8744b9ab14feb5eac572340)
2020-06-15 12:25:32+0000 [-] [Thread-2818] [anchore_engine.services.policy_engine.engine.tasks/rescan_images_created_between()] [INFO] Rescanning images loaded between 2020-06-15T12:25:05.264358 and 2020-06-15T12:25:32.491873 (operation_id=499401e7b8744b9ab14feb5eac572340)
2020-06-15 12:25:32+0000 [-] [Thread-2818] [anchore_engine.services.policy_engine.engine.tasks/rescan_images_created_between()] [INFO] Detected images: [] for rescan (operation_id=499401e7b8744b9ab14feb5eac572340)
2020-06-15 12:25:32+0000 [-] Exception in thread Thread-2818:
2020-06-15 12:25:32+0000 [-] Traceback (most recent call last):
2020-06-15 12:25:32+0000 [-]   File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
2020-06-15 12:25:32+0000 [-]     self.run()
2020-06-15 12:25:32+0000 [-]   File "/usr/lib64/python3.6/threading.py", line 864, in run
2020-06-15 12:25:32+0000 [-]     self._target(*self._args, **self._kwargs)
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/tasks.py", line 155, in <lambda>
2020-06-15 12:25:32+0000 [-]     run_target_with_lease(account=None, lease_id='feed_sync', ttl=90, target=lambda: result.append(task.execute()))
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/tasks.py", line 196, in execute
2020-06-15 12:25:32+0000 [-]     updated_dict = DataFeeds.sync(to_sync=self.feeds, full_flush=self.full_flush, catalog_client=catalog_client, operation_id=self.uuid)
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/sync.py", line 240, in sync
2020-06-15 12:25:32+0000 [-]     updated, failed = DataFeeds.sync_metadata(feed_client=feed_client, to_sync=to_sync, operation_id=operation_id)
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/sync.py", line 105, in sync_metadata
2020-06-15 12:25:32+0000 [-]     source_resp = feed_client.list_feeds()
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/client.py", line 75, in list_feeds
2020-06-15 12:25:32+0000 [-]     raise e
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/client.py", line 72, in list_feeds
2020-06-15 12:25:32+0000 [-]     'Feed list operation failed. Msg: {}. Response: {}'.format(record.get('err_msg'), record.get('text')))
2020-06-15 12:25:32+0000 [-] Exception: Feed list operation failed. Msg: None. Response: None
2020-06-15 12:25:32+0000 [-]
2020-06-15 12:25:32+0000 [-] "172.19.0.4" - - [15/Jun/2020:12:25:32 +0000] "POST /v1/feeds?force_flush=False HTTP/1.1" 200 3 "-" "python-requests/2.23.0"
2020-06-15 12:25:40+0000 [-] "172.19.0.4" - - [15/Jun/2020:12:25:40 +0000] "GET /v1/feeds?include_counts=True HTTP/1.1" 200 3 "-" "python-requests/2.23.0

**What docker images are you using**:
     Name                        Command                  State               Ports
------------------------------------------------------------------------------------------------
anchore_analyzer_1        /docker-entrypoint.sh anch ...   Up (healthy)   8228/tcp
anchore_api_1             /docker-entrypoint.sh anch ...   Up (healthy)   0.0.0.0:8228->8228/tcp
anchore_catalog_1         /docker-entrypoint.sh anch ...   Up (healthy)   8228/tcp
anchore_db_1              docker-entrypoint.sh postgres    Up             5432/tcp
anchore_policy-engine_1   /docker-entrypoint.sh anch ...   Up (healthy)   8228/tcp
anchore_queue_1           /docker-entrypoint.sh anch ...   Up (healthy)   8228/tcp

**How to reproduce the issue**:
/scratch/docker/docker-compose exec api anchore-cli system feeds sync

**Anything else we need to know**:

**Comment by navzen2000** [comment]
**Logs from policy Engine**

2020-06-15 12:25:05+0000 [-] [Thread-2818] [anchore_engine.services.policy_engine.engine.feeds.sync/sync_metadata()] [INFO] Syncing feed and group metadata from upstream source (operation_id=499401e7b8744b9ab14feb5eac572340)
2020-06-15 12:25:26+0000 [-] "127.0.0.1" - - [15/Jun/2020:12:25:26 +0000] "GET /health HTTP/1.1" 200 5 "-" "curl/7.61.1"
2020-06-15 12:25:32+0000 [-] Traceback (most recent call last):
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/client.py", line 72, in list_feeds
2020-06-15 12:25:32+0000 [-]     'Feed list operation failed. Msg: {}. Response: {}'.format(record.get('err_msg'), record.get('text')))
2020-06-15 12:25:32+0000 [-] Exception: Feed list operation failed. Msg: None. Response: None
2020-06-15 12:25:32+0000 [-] [Thread-2818] [anchore_engine.services.policy_engine.engine.feeds.client/list_feeds()] [ERROR] Error executing feed listing: Feed list operation failed. Msg: None. Response: None
2020-06-15 12:25:32+0000 [-] [Thread-2818] [anchore_engine.services.policy_engine.engine.feeds.sync/sync_metadata()] [ERROR] Rolling back feed metadata update due to error: Feed list operation failed. Msg: None. Response: None (operation_id=499401e7b8744b9ab14feb5eac572340)
2020-06-15 12:25:32+0000 [-] Traceback (most recent call last):
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/tasks.py", line 196, in execute
2020-06-15 12:25:32+0000 [-]     updated_dict = DataFeeds.sync(to_sync=self.feeds, full_flush=self.full_flush, catalog_client=catalog_client, operation_id=self.uuid)
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/sync.py", line 240, in sync
2020-06-15 12:25:32+0000 [-]     updated, failed = DataFeeds.sync_metadata(feed_client=feed_client, to_sync=to_sync, operation_id=operation_id)
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/sync.py", line 105, in sync_metadata
2020-06-15 12:25:32+0000 [-]     source_resp = feed_client.list_feeds()
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/client.py", line 75, in list_feeds
2020-06-15 12:25:32+0000 [-]     raise e
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/client.py", line 72, in list_feeds
2020-06-15 12:25:32+0000 [-]     'Feed list operation failed. Msg: {}. Response: {}'.format(record.get('err_msg'), record.get('text')))
2020-06-15 12:25:32+0000 [-] Exception: Feed list operation failed. Msg: None. Response: None
2020-06-15 12:25:32+0000 [-] [Thread-2818] [anchore_engine.services.policy_engine.engine.tasks/execute()] [ERROR] Failure refreshing and syncing feeds. (operation_id=499401e7b8744b9ab14feb5eac572340)
2020-06-15 12:25:32+0000 [-] [Thread-2818] [anchore_engine.services.policy_engine.engine.feeds.feeds/notify_event()] [INFO] Event: {"type": "system.feeds.sync.failed", "level": "error", "message": "Feeds sync task failed", "details": {"cause": "Feed list operation failed. Msg: None. Response: None", "sync_feed_types": ["vulnerabilities", "nvdv2", "github"]}, "timestamp": "2020-06-15T12:25:32.491896", "resource": {"user_id": "admin", "type": "feeds", "id": null}, "source": {"request_id": null, "servicename": "policy_engine", "hostid": "anchore-quickstart", "base_url": "http://policy-engine:8228"}} (operation_id=499401e7b8744b9ab14feb5eac572340)
2020-06-15 12:25:32+0000 [-] [Thread-2818] [anchore_engine.services.policy_engine.engine.tasks/rescan_images_created_between()] [INFO] Rescanning images loaded between 2020-06-15T12:25:05.264358 and 2020-06-15T12:25:32.491873 (operation_id=499401e7b8744b9ab14feb5eac572340)
2020-06-15 12:25:32+0000 [-] [Thread-2818] [anchore_engine.services.policy_engine.engine.tasks/rescan_images_created_between()] [INFO] Detected images: [] for rescan (operation_id=499401e7b8744b9ab14feb5eac572340)
2020-06-15 12:25:32+0000 [-] Exception in thread Thread-2818:
2020-06-15 12:25:32+0000 [-] Traceback (most recent call last):
2020-06-15 12:25:32+0000 [-]   File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
2020-06-15 12:25:32+0000 [-]     self.run()
2020-06-15 12:25:32+0000 [-]   File "/usr/lib64/python3.6/threading.py", line 864, in run
2020-06-15 12:25:32+0000 [-]     self._target(*self._args, **self._kwargs)
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/tasks.py", line 155, in <lambda>
2020-06-15 12:25:32+0000 [-]     run_target_with_lease(account=None, lease_id='feed_sync', ttl=90, target=lambda: result.append(task.execute()))
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/tasks.py", line 196, in execute
2020-06-15 12:25:32+0000 [-]     updated_dict = DataFeeds.sync(to_sync=self.feeds, full_flush=self.full_flush, catalog_client=catalog_client, operation_id=self.uuid)
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/sync.py", line 240, in sync
2020-06-15 12:25:32+0000 [-]     updated, failed = DataFeeds.sync_metadata(feed_client=feed_client, to_sync=to_sync, operation_id=operation_id)
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/sync.py", line 105, in sync_metadata
2020-06-15 12:25:32+0000 [-]     source_resp = feed_client.list_feeds()
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/client.py", line 75, in list_feeds
2020-06-15 12:25:32+0000 [-]     raise e
2020-06-15 12:25:32+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/client.py", line 72, in list_feeds
2020-06-15 12:25:32+0000 [-]     'Feed list operation failed. Msg: {}. Response: {}'.format(record.get('err_msg'), record.get('text')))
2020-06-15 12:25:32+0000 [-] Exception: Feed list operation failed. Msg: None. Response: None
2020-06-15 12:25:32+0000 [-]
2020-06-15 12:25:32+0000 [-] "172.19.0.4" - - [15/Jun/2020:12:25:32 +0000] "POST /v1/feeds?force_flush=False HTTP/1.1" 200 3 "-" "python-requests/2.23.0"
2020-06-15 12:25:40+0000 [-] "172.19.0.4" - - [15/Jun/2020:12:25:40 +0000] "GET /v1/feeds?include_counts=True HTTP/1.1" 200 3 "-" "python-requests/2.23.0

**Comment by zhill** [comment]
@navzen2000 is this still occurring? There was a temporary outage on our feed service that has been resolved.

**Comment by navzen2000** [comment]
@zhill :Yes, This is still happening.
How do I further debug it?

[service:policy-engine] 2020-06-22 08:50:53+0000 [-] [Thread-530803] [anchore_engine.services.policy_engine.engine.tasks/execute()] [INFO] Starting feed sync. (operation_id=94d7c98632bd4a9685d35eab9c6565df)
[service:policy-engine] 2020-06-22 08:50:53+0000 [-] [Thread-530803] [anchore_engine.services.policy_engine.engine.feeds.feeds/notify_event()] [INFO] Event: {"type": "system.feeds.sync.started", "level": "info", "message": "Feeds sync task started", "details": {"sync_feed_types": ["vulnerabilities", "nvdv2", "github"]}, "timestamp": "2020-06-22T08:50:53.643370", "resource": {"user_id": "admin", "type": "feeds", "id": null}, "source": {"request_id": null, "servicename": "policy_engine", "hostid": "anchore-quickstart", "base_url": "http://policy-engine:8228"}} (operation_id=94d7c98632bd4a9685d35eab9c6565df)
[service:policy-engine] 2020-06-22 08:50:53+0000 [-] [Thread-530803] [anchore_engine.services.policy_engine.engine.feeds.sync/sync()] [INFO] Performing sync of feeds: ['vulnerabilities', 'nvdv2', 'github'] (operation_id=94d7c98632bd4a9685d35eab9c6565df)
[service:policy-engine] 2020-06-22 08:50:53+0000 [-] [Thread-530803] [anchore_engine.services.policy_engine.engine.feeds.sync/sync_metadata()] [INFO] Syncing feed and group metadata from upstream source (operation_id=94d7c98632bd4a9685d35eab9c6565df)
[service:policy-engine] 2020-06-22 08:50:53+0000 [-] "127.0.0.1" - - [22/Jun/2020:08:50:53 +0000] "GET /health HTTP/1.1" 200 5 "-" "curl/7.61.1"
[service:policy-engine] 2020-06-22 08:51:18+0000 [-] Traceback (most recent call last):
[service:policy-engine] 2020-06-22 08:51:18+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/feeds/client.py", line 72, in list_feeds
[service:policy-engine] 2020-06-22 08:51:18+0000 [-]     'Feed list operation failed. Msg: {}. Response: {}'.format(record.get('err_msg'), record.get('text')))
[service:policy-engine] 2020-06-22 08:51:18+0000 [-] Exception: Feed list operation failed. Msg: None. Response: None
[service:policy-engine] 2020-06-22 08:51:18+0000 [-] [Thread-530803] [anchore_engine.services.policy_engine.engine.feeds.client/list_feeds()] [ERROR] Error executing feed listing: Feed list operation failed. Msg: None. Response: None
[service:policy-engine] 2020-06-22 08:51:18+0000 [-] [Thread-530803] [anchore_engine.services.policy_engine.engine.feeds.sync/sync_metadata()] [ERROR] Rolling back feed metadata update due to error: Feed list operation failed. Msg: None. Response: None (operation_id=94d7c98632bd4a9685d35eab9c6565df)
[service:policy-engine] 2020-06-22 08:51:18+0000 [-] Traceback (most recent call last):
[service:policy-engine] 2020-06-22 08:51:18+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/tasks.py", line 196, in execute
[service:policy-engine] 2020-06-22 08:51:18+0000 [-]     updated_dict = DataFeeds.sync(to_sync=self.feeds, full_flush=self.full_flush, catalog_client=catalog_client, operation_id=self.uuid)

**Comment by navzen2000** [comment]
@zhill This appears to be proxy issue I think. Can you point me to the container where I can set up the proxy and command to perform a manual sync directly from inside the container?

**Comment by russellgan** [comment]
@navzen2000 
Hi,I have the same issue,and now it's been resolved.It is proxy issue as you think.
My solution is add your own proxy to policy-engine enviroment ,and then add no_proxy=queue:8228,catalog:8228,localhost,registry,172.22.0.3,127.0.0.1,172.22.0.0/24,policy-engine:8228 as well.
And anlyzer enviroment should do the same thing.
Add your own proxy and no_proxy=queue:8228,catalog:8228,localhost,registry,172.22.0.3,127.0.0.1,172.22.0.0/24,policy-engine:8228 to anlyzer enviroment.

**Comment by navzen2000** [comment]
@russellgan Am using docker compose to bring up all the anchore containers, how do you specify the proxy there? Is there any config file where it can be specified?
Simply login to container and specifying proxy does not help as the python code that does the feed sync needs to make use of the proxy while containing I guess.

**Comment by russellgan** [comment]
@navzen2000 you can specify proxy in docker-compose.yaml and then restart containers.

**Comment by navzen2000** [comment]
@russellgan
Thank you very much. The solution worked for me.
@zhill :
Please update documentation to include proxy entries if needed.

**Comment by zhill** [comment]
Glad you were able to get the issue resovled @navzen2000
