### ISSUE TITLE
image scan failure on centos7 image with what appears to be a sql insert error

### ISSUE THREAD

**Issue by tonkapango** [anchore/anchore-engine#649]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG

**Version of Anchore Engine and Anchore CLI if applicable**:
anchore-cli, version 0.8.1

Service analyzer (anchore-quickstart, http://analyzer:8228): up
Service simplequeue (anchore-quickstart, http://queue:8228): up
Service apiext (anchore-quickstart, http://api:8228): up
Service policy_engine (anchore-quickstart, http://policy-engine:8228): up
Service catalog (anchore-quickstart, http://catalog:8228): up

Engine DB Version: 0.0.13
Engine Code Version: 0.8.1

**What happened**:
on image scan, of this particular centos7 image, there is a failure and we see no scan results.  looking at the logs in the policy container, it appears there is an SQL insert failure for the digest field in the image_package_db_entries table, the intended value is too large to fit in the (74) varchar type.  which is strange.  logs are truncated so we cannot see the offended row in this case.  also not sure this is underlying cause, but it is the first error that i see in the logs with this failed scan.

**What did you expect to happen**:
a correct scan completion state with either policy violation or a PASS on the policy. 

**Any relevant log output from /var/log/anchore**:

nlivic@null:~/aevolume$ anchore-cli system status
Service catalog (anchore-quickstart, http://catalog:8228): up
Service analyzer (anchore-quickstart, http://analyzer:8228): up
Service policy_engine (anchore-quickstart, http://policy-engine:8228): up
Service simplequeue (anchore-quickstart, http://queue:8228): up
Service apiext (anchore-quickstart, http://api:8228): up

Engine DB Version: 0.0.13
Engine Code Version: 0.8.1

nlivic@null:~/aevolume$ anchore-cli image add nvcr.io/nvidian/prodsec/jesus_repro:centos7
Image Digest: sha256:ecdd4eae5a1915e08601cc649b4da38d42b7e5bb1e721fb91299c2b6a928570d
Parent Digest: sha256:ecdd4eae5a1915e08601cc649b4da38d42b7e5bb1e721fb91299c2b6a928570d
Analysis Status: not_analyzed
Image Type: docker
Analyzed At: None
Image ID: 726abae61e1986fadfae83ade14a37fcacb56d1e4732b9439384ae603b539be9
Dockerfile Mode: Guessed
Distro: centos
Distro Version: 7
Size: 4557352960
Architecture: amd64
Layer Count: 8

Full Tag: nvcr.io/nvidian/prodsec/jesus_repro:centos7
Tag Detected At: 2020-10-06T16:17:09Z

nlivic@null:~/aevolume$ anchore-cli image wait nvcr.io/nvidian/prodsec/jesus_repro:centos7
Status: analyzing
Waiting 5.0 seconds for next retry.
Status: analyzing
Waiting 5.0 seconds for next retry.
Status: analyzing
Waiting 5.0 seconds for next retry.
......[truncated] ........
Waiting 5.0 seconds for next retry.
Error: Requested image not found on system

======================
anchore-policy logs
first error in logs for this image

2020-10-06 16:22:38+0000 [-] [SQL: INSERT INTO image_package_db_entries (image_id, image_user_id, pkg_name, pkg_version, pkg_
type, pkg_arch, pkg_path, file_path, is_config_file, digest, digest_algorithm, file_group_name, file_user_name, mode, size) V
ALUES (%(image_id)s, %(image_user_id)s, %(pkg_name)s, %(pkg_version)s, %(pkg_type)s, %(pkg_arch)s, %(pkg_path)s, %(file_path)
s, %(is_config_file)s, %(digest)s, %(digest_algorithm)s, %(file_group_name)s, %(file_user_name)s, %(mode)s, %(size)s)]
2020-10-06 16:22:38+0000 [-] [parameters: ({'image_id': '726abae61e1986fadfae83ade14a37fcacb56d1e4732b9439384ae603b539be9', '
image_user_id': 'admin', 'pkg_name': 'acl', 'pkg_version': '2.2.51', 'pkg_type': 'rpm', 'pkg_arch': 'x86_64', 'pkg_path': 'pk
gdb', 'file_path': '/usr/bin/chacl', 'is_config_file': False, 'digest': 'f2533e2717c478adc0f2bfcf4043472b0b3750b268f28ba1fef1
f36eae51c764', 'digest_algorithm': 'sha256', 'file_group_name': 'root', 'file_user_name': 'root', 'mode': 33261, 'size': 1563
2}, {'image_id': '726abae61e1986fadfae83ade14a37fcacb56d1e4732b9439384ae603b539be9', 'image_user_id': 'admin', 'pkg_name': 'a
cl', 'pkg_version': '2.2.51', 'pkg_type': 'rpm', 'pkg_arch': 'x86_64', 'pkg_path': 'pkgdb', 'file_path': '/usr/bin/getfacl',
'is_config_file': False, 'digest': '666ab0ef36347edf002783c974be045b678221e1685a044d8851307b12f9b2a2', 'digest_algorithm': 's
ha256', 'file_group_name': 'root', 'file_user_name': 'root', 'mode': 33261, 'size': 24872}, {'image_id': '726abae61e1986fadfa
e83ade14a37fcacb56d1e4732b9439384ae603b539be9', 'image_user_id': 'admin', 'pkg_name': 'acl', 'pkg_version': '2.2.51', 'pkg_ty
pe': 'rpm', 'pkg_arch': 'x86_64', 'pkg_path': 'pkgdb', 'file_path': '/usr/bin/setfacl', 'is_config_file': False, 'digest': '6
bb98071fc92f94d80131f339789682b45d73503841067421b195a39b1770874', 'digest_algorithm': 'sha256', 'file_group_name': 'root', 'f
ile_user_name': 'root', 'mode': 33261, 'size': 37608}, {'image_id': '726abae61e1986fadfae83ade14a37fcacb56d1e4732b9439384ae60
3b539be9', 'image_user_id': 'admin', 'pkg_name': 'acl', 'pkg_version': '2.2.51', 'pkg_type': 'rpm', 'pkg_arch': 'x86_64', 'pk
g_path': 'pkgdb', 'file_path': '/usr/share/doc/acl-2.2.51', 'is_config_file': False, 'digest': None, 'digest_algorithm': 'sha
256', 'file_group_name': 'root', 'file_user_name': 'root', 'mode': 16877, 'size': 4096}, {'image_id': '726abae61e1986fadfae83
ade14a37fcacb56d1e4732b9439384ae603b539be9', 'image_user_id': 'admin', 'pkg_name': 'acl', 'pkg_version': '2.2.51', 'pkg_type'
: 'rpm', 'pkg_arch': 'x86_64', 'pkg_path': 'pkgdb', 'file_path': '/usr/share/doc/acl-2.2.51/CHANGES.gz', 'is_config_file': Fa
lse, 'digest': '9f0c057b937132de1f8752cafa602bb2b5a2adc65fb2893adb5f22c9289aa747', 'digest_algorithm': 'sha256', 'file_group_
name': 'root', 'file_user_name': 'root', 'mode': 33188, 'size': 8296}, {'image_id': '726abae61e1986fadfae83ade14a37fcacb56d1e
4732b9439384ae603b539be9', 'image_user_id': 'admin', 'pkg_name': 'acl', 'pkg_version': '2.2.51', 'pkg_type': 'rpm', 'pkg_arch
': 'x86_64', 'pkg_path': 'pkgdb', 'file_path': '/usr/share/doc/acl-2.2.51/COPYING', 'is_config_file': False, 'digest': 'a45a8
45012742796534f7e91fe623262ccfb99460a2bd04015bd28d66fba95b8', 'digest_algorithm': 'sha256', 'file_group_name': 'root', 'file_
user_name': 'root', 'mode': 33188, 'size': 18311}, {'image_id': '726abae61e1986fadfae83ade14a37fcacb56d1e4732b9439384ae603b53
9be9', 'image_user_id': 'admin', 'pkg_name': 'acl', 'pkg_version': '2.2.51', 'pkg_type': 'rpm', 'pkg_arch': 'x86_64', 'pkg_pa
th': 'pkgdb', 'file_path': '/usr/share/doc/acl-2.2.51/COPYING.LGPL', 'is_config_file': False, 'digest': '01b1f9f2c8ee648a7a59
6a1abe8aa4ed7899b1c9e5551bda06da6e422b04aa55', 'digest_algorithm': 'sha256', 'file_group_name': 'root', 'file_user_name': 'ro
ot', 'mode': 33188, 'size': 26762}, {'image_id': '726abae61e1986fadfae83ade14a37fcacb56d1e4732b9439384ae603b539be9', 'image_u
ser_id': 'admin', 'pkg_name': 'acl', 'pkg_version': '2.2.51', 'pkg_type': 'rpm', 'pkg_arch': 'x86_64', 'pkg_path': 'pkgdb', '
file_path': '/usr/share/doc/acl-2.2.51/PORTING', 'is_config_file': False, 'digest': '270d640aae568b3e69f818cd2b69040d0682f2cb
2a0b3f383bf42fb771b356b3', 'digest_algorithm': 'sha256', 'file_group_name': 'root', 'file_user_name': 'root', 'mode': 33188,
'size': 3208}  ... displaying 10 of 30970 total bound parameter sets ...  {'image_id': '726abae61e1986fadfae83ade14a37fcacb56
d1e4732b9439384ae603b539be9', 'image_user_id': 'admin', 'pkg_name': 'yum-metadata-parser', 'pkg_version': '1.1.4', 'pkg_type'
: 'python', 'pkg_arch': 'N/A', 'pkg_path': '/usr/lib64/python2.7/site-packages/yum-metadata-parser', 'file_path': '/usr/share
/doc/yum-metadata-parser-1.1.4/ChangeLog', 'is_config_file': False, 'digest': 'bcd47f26bfe8ffba721bfac2ab16f9a751cdb78aa7acb3
7dd6b3f48984109dc4', 'digest_algorithm': 'sha256', 'file_group_name': 'root', 'file_user_name': 'root', 'mode': 33188, 'size'
: 2934}, {'image_id': '726abae61e1986fadfae83ade14a37fcacb56d1e4732b9439384ae603b539be9', 'image_user_id': 'admin', 'pkg_name
': 'yum-metadata-parser', 'pkg_version': '1.1.4', 'pkg_type': 'python', 'pkg_arch': 'N/A', 'pkg_path': '/usr/lib64/python2.7/
site-packages/yum-metadata-parser', 'file_path': '/usr/share/doc/yum-metadata-parser-1.1.4/README', 'is_config_file': False,
'digest': 'dc4844555c1255aecf4dda39a800f51473a2cfb89b16a640af3051b23a0b4e1b', 'digest_algorithm': 'sha256', 'file_group_name'
: 'root', 'file_user_name': 'root', 'mode': 33188, 'size': 658})]
2020-10-06 16:22:38+0000 [-] (Background on this error at: http://sqlalche.me/e/9h9h)
2020-10-06 16:22:38+0000 [_GenericHTTPChannelProtocol,41,172.18.0.7] [PoolThread-twisted.internet.reactor-0] [anchore_engine.
services.policy_engine.engine.vulnerabilities/vulnerabilities_for_image()] [ERROR] Error computing full vulnerability set for
 image admin/726abae61e1986fadfae83ade14a37fcacb56d1e4732b9439384ae603b539be9

2020-10-06 16:22:38+0000 [-] Traceback (most recent call last):
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1226, in _exec
ute_context
2020-10-06 16:22:38+0000 [-]     cursor, statement, parameters, context
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", li
ne 854, in do_executemany
2020-10-06 16:22:38+0000 [-]     cursor.executemany(statement, parameters)
2020-10-06 16:22:38+0000 [-] psycopg2.errors.StringDataRightTruncation: value too long for type character varying(74)
2020-10-06 16:22:38+0000 [-]
2020-10-06 16:22:38+0000 [-]
2020-10-06 16:22:38+0000 [-] The above exception was the direct cause of the following exception:
2020-10-06 16:22:38+0000 [-]
2020-10-06 16:22:38+0000 [-] Traceback (most recent call last):
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/task
s.py", line 384, in execute
2020-10-06 16:22:38+0000 [-]     vulns = vulnerabilities_for_image(image_obj)
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/services/policy_engine/engine/vuln
erabilities.py", line 186, in vulnerabilities_for_image
2020-10-06 16:22:38+0000 [-]     for package in image_obj.packages:
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/dynamic.py", line 304, in __iter
__

2020-10-06 16:22:38+0000 [-]     sess = self.session
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/dynamic.py", line 295, in sessio
n
2020-10-06 16:22:38+0000 [-]     sess.flush()
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2479, in flush
2020-10-06 16:22:38+0000 [-]     self._flush(objects)
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2617, in _flus
h
2020-10-06 16:22:38+0000 [-]     transaction.rollback(_capture_exception=True)
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __
exit__
2020-10-06 16:22:38+0000 [-]     compat.reraise(exc_type, exc_value, exc_tb)
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in rerais
e
2020-10-06 16:22:38+0000 [-]     raise value
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2577, in _flus
h
2020-10-06 16:22:38+0000 [-]     flush_context.execute()
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in exe
cute
2020-10-06 16:22:38+0000 [-]     rec.execute(self)
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in exe
cute
2020-10-06 16:22:38+0000 [-]     uow,
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in sa
ve_obj
2020-10-06 16:22:38+0000 [-]     insert,
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1084, in _
emit_insert_statements
2020-10-06 16:22:38+0000 [-]     c = cached_connections[connection].execute(statement, multiparams)
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 982, in execut
e
2020-10-06 16:22:38+0000 [-]     return meth(self, multiparams, params)
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _exec
ute_on_connection
2020-10-06 16:22:38+0000 [-]     return connection._execute_clauseelement(self, multiparams, params)
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1101, in _exec
ute_clauseelement
2020-10-06 16:22:38+0000 [-]     distilled_params,
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1250, in _exec
ute_context
2020-10-06 16:22:38+0000 [-]     e, statement, parameters, cursor, context
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _hand
le_dbapi_exception
2020-10-06 16:22:38+0000 [-]     util.raise_from_cause(sqlalchemy_exception, exc_info)
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_
from_cause
2020-10-06 16:22:38+0000 [-]     reraise(type(exception), exception, tb=exc_tb, cause=cause)
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in rerais
e
2020-10-06 16:22:38+0000 [-]     raise value.with_traceback(tb)
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1226, in _exec
ute_context

2020-10-06 16:22:38+0000 [-]     raise value.with_traceback(tb)
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1226, in _exec
ute_context
2020-10-06 16:22:38+0000 [-]     cursor, statement, parameters, context
2020-10-06 16:22:38+0000 [-]   File "/usr/local/lib64/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", li
ne 854, in do_executemany
2020-10-06 16:22:38+0000 [-]     cursor.executemany(statement, parameters)
2020-10-06 16:22:38+0000 [-] sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type ch
aracter varying(74)

===========================

nlivic@null:~/$ docker inspect gitlab-master.nvidia.com:5005/cuda-installer/cuda:11.1-devel-centos7
[
    {
        "Id": "sha256:726abae61e1986fadfae83ade14a37fcacb56d1e4732b9439384ae603b539be9",
        "RepoTags": [
            "gitlab-master.nvidia.com:5005/cuda-installer/cuda:11.1-devel-centos7",
            "nvcr.io/nvidian/prodsec/jesus_repro:centos7"
        ],
        "RepoDigests": [
            "gitlab-master.nvidia.com:5005/cuda-installer/cuda@sha256:c32df678c6e0c17ddfce7091bc3d98fad0f7c8e8de8c9129f1577b65db738078",
            "nvcr.io/nvidian/prodsec/jesus_repro@sha256:ecdd4eae5a1915e08601cc649b4da38d42b7e5bb1e721fb91299c2b6a928570d"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2020-10-04T05:57:00.033831291Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "CUDA_VERSION=11.1.0",
                "LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64",
                "NVIDIA_VISIBLE_DEVICES=all",
                "NVIDIA_DRIVER_CAPABILITIES=compute,utility",
                "NVIDIA_REQUIRE_CUDA=cuda>=11.1 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441",
                "NCCL_VERSION=2.7.8",
                "LIBRARY_PATH=/usr/local/cuda/lib64/stubs"
            ],
            "Cmd": [
                "/bin/bash"
            ],
            "ArgsEscaped": true,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "maintainer": "NVIDIA CORPORATION <sw-cuda-installer@nvidia.com>",
                "org.label-schema.build-date": "20200809",
                "org.label-schema.license": "GPLv2",
                "org.label-schema.name": "CentOS Base Image",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vendor": "CentOS",
                "org.opencontainers.image.created": "2020-08-09 00:00:00+01:00",
                "org.opencontainers.image.licenses": "GPL-2.0-only",
                "org.opencontainers.image.title": "CentOS Base Image",
                "org.opencontainers.image.vendor": "CentOS"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 4602117480,
        "VirtualSize": 4602117480,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/dbf9d7b9004d344a42881ee2aa6a791275b08249c10fa6b279b174fa9445d43a/diff:/var/lib/docker/overlay2/e9cf7b4f733846b420e60d16b66e26acc49b3b882757aa1cbc32c78b89972263/diff:/var/lib/docker/overlay2/efa455fc63bcc7cf58b48ab7b6077aacf405d33a4f367ff2f0a48e50ebbeae7d/diff:/var/lib/docker/overlay2/adc7808e91262ca5bd6391656f076a4827fce20bcd2e3336ad41f222fdd52f15/diff:/var/lib/docker/overlay2/c507529b42641768c6a1cca967b9f117e94c95c50bbfecf92affb99f087b8c22/diff:/var/lib/docker/overlay2/e40dd214b0ffbdad51a55f537419ac20a1b73b411ee5a47ea070d0792db0a056/diff:/var/lib/docker/overlay2/4c93f2403db55fcc8a0d34559fa1bcaa26289ed7427e9ca7a744409dea856117/diff",
                "MergedDir": "/var/lib/docker/overlay2/217153157cc1e898c9a4964dd91190535e6e30da5e9c17e6162bbd8111bdcda0/merged",
                "UpperDir": "/var/lib/docker/overlay2/217153157cc1e898c9a4964dd91190535e6e30da5e9c17e6162bbd8111bdcda0/diff",
                "WorkDir": "/var/lib/docker/overlay2/217153157cc1e898c9a4964dd91190535e6e30da5e9c17e6162bbd8111bdcda0/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:613be09ab3c0860a5216936f412f09927947012f86bfa89b263dfa087a725f81",
                "sha256:256ef3ebb14be049cec5c290d6e45124319f162f2b5161ef3a4d4eb79d9eb1d2",
                "sha256:79bcf532a2e7981e44780b6b5bb5a5801ce9c6ff8adae2088cfafcd9caa06421",
                "sha256:00bad7abfbb301f42a583e7608a70da738968c2f0057cd13b411cc544a3c059c",
                "sha256:5efd1be7047f16ac570291f5fe099be6f760e640e6ac520ac6c72d4cdbf4b770",
                "sha256:654545b9fa82e7d17f95fe6d31fad61f29ebbfc06b2125a33302cfeb285f77f4",
                "sha256:82b53eaaca08ea9800b08ccfd7fbab9f67cb2209aeaef3b87ee5e40abba5b819",
                "sha256:44ab77a0c83e0426516de175035f5627da6477966c790dda788058e9db93eb6b"
            ]
        },
        "Metadata": {
            "LastTagTime": "2020-10-06T11:09:10.37023118-05:00"
        }
    }
]

**What docker images are you using**:

**How to reproduce the issue**:
i can push the image to a registry of your choice if you want.

**Anything else we need to know**:

**Comment by zhill** [comment]
Thanks @tonkapango we'll take a look and see which field is failing the insert

**Comment by zhill** [comment]
Closed by #755
