### ISSUE TITLE
could not construct service base_url - please check service configuration for hostname/port settings

### ISSUE THREAD

**Issue by jbouse** [anchore/anchore-engine#67]
**Version of Anchore Engine and Anchore CLI if applicable**:

```
sh-4.2# anchore-cli --version
anchore-cli, version 0.2.2
```
```
sh-4.2# pip show anchore-engine
Name: anchore-engine
Version: 0.2.2
Summary: Anchore Engine
Home-page: http://www.anchore.com
Author: Anchore Inc.
Author-email: dev@anchore.com
License: Apache License 2.0
Location: /usr/lib/python2.7/site-packages
Requires: Twisted, pg8000, boto3, botocore, chardet, click, clickclick, connexion, docker-py, enum34, docutils, Flask, functools32, futures, idna, inflection, itsdangerous, Jinja2, jmespath, jsonschema, MarkupSafe, pathlib, python-dateutil, PyYAML, requests, s3transfer, six, SQLAlchemy, swagger-spec-validator, typing, urllib3, watchdog, Werkzeug, passlib, prometheus-client, prometheus-flask-exporter, python-swiftclient, python-keystoneclient, pytz, certifi
Required-by: 
```
 
**What happened**:

Upgraded from v0.2.1 to v0.2.2 Docker image and all services came back online except the analyzer service.

**What did you expect to happen**:

Expectation was that the analyzer worker service would come back online along with the other services.

**Any relevant log output from /var/log/anchore**:

```
[MainThread] [anchore_manager.cli.utils/connect_database()] [INFO] DB connection configured: True
[MainThread] [anchore_manager.cli.utils/connect_database()] [INFO] DB attempting to connect...
[MainThread] [anchore_manager.cli.utils/connect_database()] [INFO] DB connected: True
[MainThread] [anchore_manager.cli.utils/init_database()] [INFO] DB compatibility check: running...
[MainThread] [anchore_manager.cli.utils/init_database()] [INFO] DB compatibility check success
[MainThread] [anchore_manager.cli.utils/init_database()] [INFO] DB post actions: running...
[MainThread] [anchore_manager.cli.service/start()] [INFO] DB version and code version in sync.
[MainThread] [anchore_manager.cli.service/start()] [INFO] Starting services: ['anchore-worker']
[anchore-worker] [anchore_manager.cli.service/startup_service()] [INFO] cleaning up service: anchore-worker
[anchore-worker] [anchore_manager.cli.service/startup_service()] [INFO] starting service: anchore-worker
[anchore-worker] [anchore_manager.cli.service/startup_service()] [INFO] /bin/twistd --logger=anchore_engine.subsys.twistd_logger.logger --pidfile /var/run/anchore-worker.pid -n anchore-worker --config /config
[service:analyzer] 2018-06-18 14:28:59+0000 [-] [bootstrap] [WARNING] no webhooks defined in configuration file - notifications will be disabled
[service:analyzer] 2018-06-18 14:28:59+0000 [-] [bootstrap] [INFO] initializing database
[service:analyzer] 2018-06-18 14:28:59+0000 [-] [bootstrap] [ERROR] cannot create/init/register service: analyzer - exception: could not construct service base_url - please check service configuration for hostname/port settings
[service:analyzer] 2018-06-18 14:28:59+0000 [-] [bootstrap] [ERROR] cannot start service (see above for information)
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/anchore_engine/services/common.py", line 366, in makeService
rc = smodule.registerService(sname, localconfig)
File "/usr/lib/python2.7/site-packages/anchore_engine/services/analyzer/__init__.py", line 112, in registerService
rc = anchore_engine.services.common.registerService(sname, config, enforce_unique=False)
File "/usr/lib/python2.7/site-packages/anchore_engine/services/common.py", line 197, in registerService
raise Exception("could not construct service base_url - please check service configuration for hostname/port settings")
Exception: could not construct service base_url - please check service configuration for hostname/port settings
Traceback (most recent call last):
File "/bin/twistd", line 11, in <module>
load_entry_point('Twisted==17.5.0', 'console_scripts', 'twistd')()
File "/usr/lib64/python2.7/site-packages/twisted/scripts/twistd.py", line 29, in run
app.run(runApp, ServerOptions)
File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 662, in run
runApp(config)
File "/usr/lib64/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
_SomeApplicationRunner(config).run()
File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 380, in run
self.application = self.createOrGetApplication()
File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 440, in createOrGetApplication
ser = plg.makeService(self.config.subOptions)
File "/usr/lib/python2.7/site-packages/twisted/plugins/anchore_worker.py", line 82, in makeService
r = anchore_engine.services.common.makeService(slist, options)
File "/usr/lib/python2.7/site-packages/anchore_engine/services/common.py", line 387, in makeService
raise Exception("cannot start service (see above for information)")
Exception: cannot start service (see above for information)
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/anchore_manager/cli/service.py", line 140, in startup_service
raise Exception("process exited: " + str(rc))
Exception: process exited: 1
[anchore-worker] [anchore_manager.cli.service/startup_service()] [INFO] service process exited at (Mon Jun 18 14:28:59 2018): process exited: 1
[anchore-worker] [anchore_manager.cli.service/startup_service()] [INFO] exiting service thread
```

**What docker images are you using**:

Docker Hub image anchore/anchore-engine:v0.2.2

**How to reproduce the issue**:

Launch with services running in separate containers and analyzer service fails to start with the above error

**Anything else we need to know**:

config.yaml in use on analyzer service container:

```
# Anchore Service Configuration File

# General system-wide configuration options, these should not need to
# be altered for basic operation
#
# service_dir: '/config'
# tmp_dir: '/tmp'
# log_level: 'DEBUG'
#
allow_awsecr_iam_auto: True
cleanup_images: True
# docker_conn: 'unix://var/run/docker.sock'
# docker_conn_timeout: 600
#
#
log_level: 'INFO'
# log_level: 'DEBUG'

# This is necessary to ensure that a re-start of the pod on another host works. The string can be anything, but should be explicitly set to identify the host.
# host_id: ${ANCHORE_HOST_ID} 
internal_ssl_verify: False

# Uncomment if you have a local endpoint that can accept
# notifications from the anchore-engine, as configured below
#
#webhooks:
#  webhook_user: 'user'
#  webhook_pass: 'pass'
#  ssl_verify: False
#  general:
#    url: 'http://localhost:9090/general/<notification_type>/<userId>'
#  policy_eval:
#    url: 'http://localhost:9090/policy_eval/<userId>'
#    webhook_user: 'mehuser'
#    webhook_pass: 'mehpass'
## special webhook for FATAL service events - system will store in DB if not enabled here
#  # error_event:
#  #   url: 'http://localhost:9090/error_event/'
#  #

#
# A feeds section is available for override, but shouldn't be
# needed. By default, the 'admin' credentials are used if present,
# otherwise anonymous access for feed sync is used

#feeds:
#  selective_sync:
#    # If enabled only sync specific feeds instead of all.
#    enabled: True
#    feeds:
#      vulnerabilities: True
#      # Warning: enabling the package sync causes the service to require much
#      #   more memory to do process the significant data volume. We recommend at least 4GB available for the container
#      packages: False
#  anonymous_user_username: anon@ancho.re
#  anonymous_user_password: pbiU2RYZ2XrmYQ
#  url: 'https://ancho.re/v1/service/feeds'
#  client_url: 'https://ancho.re/v1/account/users'
#  token_url: 'https://ancho.re/oauth/token'
#  connection_timeout_seconds: 3
#  read_timeout_seconds: 60

credentials:
  users:
     admin:
       password: ${ANCHORE_ADMIN_PASSWORD}
       email: '${ANCHORE_ADMIN_EMAIL}'
       external_service_auths:
       #  anchoreio:
       #    anchorecli:
       #      auth: 'myanchoreiouser:myanchoreiopass'
       #auto_policy_sync: True

  database:
    db_connect: "postgresql+pg8000://${ANCHORE_DB_USER}:${ANCHORE_DB_PASSWORD}@${ANCHORE_DB_POSTGRESQL_SERVICE_HOST}:${ANCHORE_DB_POSTGRESQL_SERVICE_PORT}/${ANCHORE_DB_NAME}"
    db_connect_args:
      timeout: 120
      ssl: False
    db_pool_size: 30
    db_pool_max_overflow: 100

services:
  apiext:
    enabled: False
    require_auth: True
    endpoint_hostname: ${ANCHORE_ENGINE_SERVICE_SERVICE_HOST}
    listen: '0.0.0.0'
    port: 8228
    # ssl_enable: True
  kubernetes_webhook:
    enabled: False
    require_auth: False
    endpoint_hostname: ${ANCHORE_ENGINE_SERVICE_SERVICE_HOST}
    listen: '0.0.0.0'
    port: 8338
    # ssl_enable: True
  catalog:
    enabled: False
    require_auth: True
    endpoint_hostname: ${ANCHORE_ENGINE_SERVICE_SERVICE_HOST}
    listen: '0.0.0.0'
    port: 8082
    use_db: True
    cycle_timer_seconds: '1'
    cycle_timers:
      image_watcher: 3600
      policy_eval: 3600
      feed_sync: 14400
      analyzer_queue: 1
      notifications: 30
      service_watcher: 15
      policy_bundle_sync: 300
  simplequeue:
    enabled: False
    require_auth: True
    endpoint_hostname: ${ANCHORE_ENGINE_SERVICE_SERVICE_HOST}
    listen: '0.0.0.0'
    port: 8083
  analyzer:
    enabled: True
    cycle_timer_seconds: '1'
    max_threads: '1'
    analyzer_driver: 'nodocker'
  policy_engine:
    enabled: False
    require_auth: True
    endpoint_hostname: ${ANCHORE_ENGINE_SERVICE_SERVICE_HOST}
    listen: '0.0.0.0'
    port: 8087
    # ssl_enable: True
```

Environment variables set:

```
ANCHORE_ENGINE_SERVICES=anchore-worker
ANCHORE_DB_POSTGRESQL_SERVICE_PORT=5432
ANCHORE_HOST_ID=anchore-dev
ANCHORE_ENGINE_SERVICE_SERVICE_HOST=anchore.example.com
ANCHORE_ADMIN_PASSWORD=****
ANCHORE_DB_USER=****
ANCHORE_DB_NAME=anchore
ANCHORE_DB_PASSWORD=****
ANCHORE_DB_POSTGRESQL_SERVICE_HOST=anchore-db.example.com
ANCHORE_ADMIN_EMAIL=jdoe@example.com
```

**Comment by jbouse** [comment]
Okay appears to be related to upgrade requiring the addition of `endpoint_hostname`, `listen` and `port` options being added to the analyzer service

**Comment by nurmi** [comment]
Thanks @jbouse - I'd like to note that, as a followup, I think we need to add a better message since the config validation should have failed and caught this condition, but it currently does not (cleanly) - I've prototyped a better check/message that looks like this (for example), right away when the service tries to start (which also prevents the service from starting, cleanly):

```
[MainThread] [anchore_manager.cli.service/start()] [ERROR] Error: cannot load local configuration: invalid configuration: details - the following values '['endpoint_hostname', 'listen', 'port']' must be set for all services, but service 'analyzer' does not have them set (missing 'endpoint_hostname')
```

**Comment by jbouse** [comment]
@nurmi Is `endpoint_hostname` and `port` required if `external_hostname` and `external_port` are used or are they they optional and `endpoint_hostname` and `port` are required?

**Comment by nurmi** [comment]
@jbouse - they still are - the 'port' will be the port that is actually bound in the container, regardless of the external_* settings (which are just overrides for the endpoint_hostname/port settings, communicating that outside services should use other values to reach this service (if, say, they're behind an LB with a different port/hostname and the internal port/hostname cannot be set to those values exactly for any reason)
