### ISSUE TITLE
analyzers: (syft) java breaks while trying to figure out the extension

### ISSUE THREAD

**Issue by alfredodeza** [anchore/anchore-engine#748]
**What happened**: Analyzing `openjdk:latest` breaks the Java analyzer

**Any relevant log output from /var/log/anchore**:

```
Traceback (most recent call last):
2020-12-01 07:13:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/clients/localanchore_standalone.py", line 1257, in analyze_image
2020-12-01 07:13:34+0000 [-]     staging_dirs, imageDigest, imageId, localconfig
2020-12-01 07:13:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/clients/localanchore_standalone.py", line 1052, in run_anchore_analyzers
2020-12-01 07:13:34+0000 [-]     image=copydir, unpackdir=unpackdir
2020-12-01 07:13:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/analyzers/syft/__init__.py", line 37, in catalog_image
2020-12-01 07:13:34+0000 [-]     handler.translate_and_save_entry(findings, artifact)
2020-12-01 07:13:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/anchore_engine/analyzers/syft/handlers/java.py", line 30, in translate_and_save_entry
2020-12-01 07:13:34+0000 [-]     java_ext = virtualElements[-2].split(".")[-1]
2020-12-01 07:13:34+0000 [-] IndexError: list index out of range
```

**What docker images are you using**:

**How to reproduce the issue**: in functional tests, find the standalone.py script:

```
$ python standalone.py --repo openjdk --tag=latest --digest=sha256:f0c1de9259745d085481a3201b9093205afc4d7d719f45f4fcc021767642a542
```

**Anything else we need to know**:

**Comment by alfredodeza** [comment]
@dakaneye I am unable to replicate this problem using `openjdk:latest` with a digest of `=sha256:f0c1de9259745d085481a3201b9093205afc4d7d719f45f4fcc021767642a542` . Did you modified that image at all? Or perhaps you used something different?

**Comment by dakaneye** [comment]
@alfredodeza, nope just used openjdk latest!

Here's a bit more of the logs from the execution error: 
```
Exception: java analyzer broke, virtualElements is: ['N/A'], artifact is {
   "name":"Java Runtime Environment",
   "version":"15.0.1",
   "type":"java-archive",
   "foundBy":[
      "java-cataloger"
   ],
   "locations":[
      {
         "path":"/usr/java/openjdk-15/lib/jrt-fs.jar",
         "layerIndex":2
      }
   ],
   "metadata":{
      "manifest":{
         "name":"",
         "manifestVersion":"1.0",
         "specificationTitle":"Java Platform API Specification",
         "specificationVersion":"15",
         "specificationVendor":"Oracle Corporation",
         "implementationTitle":"Java Runtime Environment",
         "implementationVersion":"15.0.1",
         "implementationVendor":"Oracle Corporation",
         "extraFields":{
            "Created-By":"14 (Oracle Corporation)"
         }
      },
      "pomProperties":"None",
      "parentPackage":"None"
   }
```
Digest is `sha256:06bd36ad06e052ea3ec0cc18c971a2e514d57c7a80764d9469dc86ecb650dc4d`

**Comment by alfredodeza** [comment]
This ended up being caused by a very old version of `syft` which will not work. Closing this. Thanks for debugging @dakaneye
