### ISSUE TITLE
Connecting externally with java API - ssl in place ?

### ISSUE THREAD

**Issue by SyCode7** [anchore/anchore-engine#90]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one):
Bug report

**Version of Anchore Engine and Anchore CLI if applicable**:

  version 0.3.0-dev
**What happened**:
Connecting externally with java API  fails, I am not sure if ssl enforced but I set ssl to false i.e. `external_tls: False` in the config.yaml file. Connecting both locally, i.e. on same machine and remote host fail.

**What did you expect to happen**:
I expect the connection to be seamless, even `curl` to the remote anchore server fails.

**Any relevant log output from /var/log/anchore**:

`Exception in thread "main" io.swagger.client.ApiException: java.net.SocketTimeoutException: Read timed out
	at io.swagger.client.ApiClient.execute(ApiClient.java:842)
	at io.swagger.client.api.VulnerabilitiesApi.getImageVulnerabilitiesByTypeWithHttpInfo(VulnerabilitiesApi.java:142)
	at io.swagger.client.api.VulnerabilitiesApi.getImageVulnerabilitiesByType(VulnerabilitiesApi.java:127)
	at io.cavasTest.CavasTest.main(CavasTest.java:46)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.squareup.okhttp.Call.getResponse(Call.java:286)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at io.swagger.client.ApiClient.execute(ApiClient.java:838)
	... 3 more
`
**What docker images are you using**:

**How to reproduce the issue**:

**Anything else we need to know**:

**stacktrace of connection failure against the remote anchore server :**

`Exception in thread "main" io.swagger.client.ApiException: java.net.ConnectException: Failed to connect to seclab.hpi.uni-potsdam.de/172.16.22.111:50097
	at io.swagger.client.ApiClient.execute(ApiClient.java:842)
	at io.swagger.client.api.VulnerabilitiesApi.getImageVulnerabilitiesByTypeWithHttpInfo(VulnerabilitiesApi.java:142)
	at io.swagger.client.api.VulnerabilitiesApi.getImageVulnerabilitiesByType(VulnerabilitiesApi.java:127)
	at io.cavasTest.CavasTest.main(CavasTest.java:46)
Caused by: java.net.ConnectException: Failed to connect to seclab.hpi.uni-potsdam.de/172.16.22.111:50097
	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.squareup.okhttp.Call.getResponse(Call.java:286)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at io.swagger.client.ApiClient.execute(ApiClient.java:838)
	... 3 more
`

**Comment by nurmi** [comment]
hi @SyCode7 - we wanted to check in to see if there are any updates on progress for this issue (and if we can help if there still are!)

**Comment by zhill** [comment]
Due to inactivity, I'm closing this issue. @SyCode7 if there is still a problem, please re-open.
