### ISSUE TITLE
Image failed analysis unpacking from private repository

### ISSUE THREAD

**Issue by agentreno** [anchore/anchore-engine#92]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or a FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Anchore Engine and Anchore CLI if applicable**:
anchore-cli: 0.3.0-dev
anchore-engine: 0.2.4
 
**What happened**:
Image analysis failed for an image in a private repository. The registry is unauthenticated so I'm led to believe I don't need to add the registry with anchore-cli, since there is no user/pass to provide.

**What did you expect to happen**:
For anchore-engine to fetch the image based on the registry in the image name (<registry-domain>/image-name:tag) and run analysis.

**Any relevant log output from /var/log/anchore**:
2018-09-27 12:53:39+0000 [-] Traceback (most recent call last):
2018-09-27 12:53:39+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/analyzer/__init__.py", line 321, in process_analyzer_job
2018-09-27 12:53:39+0000 [-]     image_data = perform_analyze(userId, manifest, image_record, registry_creds, layer_cache_enable=layer_cache_enable)
2018-09-27 12:53:39+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/analyzer/__init__.py", line 142, in perform_analyze
2018-09-27 12:53:39+0000 [-]     return(perform_analyze_nodocker(userId, manifest, image_record, registry_creds, layer_cache_enable=layer_cache_enable))
2018-09-27 12:53:39+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/services/analyzer/__init__.py", line 181, in perform_analyze_nodocker
2018-09-27 12:53:39+0000 [-]     analyzed_image_report = localanchore_standalone.analyze_image(userId, registry_manifest, image_record, tmpdir, localconfig, registry_creds=registry_creds, use_cache_dir=use_cache_dir)
2018-09-27 12:53:39+0000 [-]   File "/usr/lib/python2.7/site-packages/anchore_engine/clients/localanchore_standalone.py", line 744, in analyze_image
2018-09-27 12:53:39+0000 [-]     raise ImageUnpackError(cause=err, pull_string=pullstring, tag=fulltag)
2018-09-27 12:53:39+0000 [-] ImageUnpackError: Failed to unpack image (*image name redacted*) - exception: command failed: cmd=tar -C /tmp/8a1f9d76-a36c-4bf4-965f-ee428d2770cd/rootfs -x -X /tmp/8a1f9d76-a36c-4bf4-965f-ee428d2770cd/efile -f /tmp/8a1f9d76-a36c-4bf4-965f-ee428d2770cd/raw/blobs/sha256/0988bfabde1493909210bce6cfefab305b05f07b1e91a42700a12fdc7896d3f5 exitcode=2 stdout= stderr=tar: usr/sbin: Directory renamed before its status could be extracted

**What docker images are you using**:
A private image in a private repository. Apologies, I'm unable to share info about the image. I can confirm though that the issue doesn't occur with images from a public registry.

**How to reproduce the issue**:
It would be hard for you to reproduce the issue, I know that's a pain, any pointers you can give me based on the log output above would be helpful.

**Anything else we need to know**:

**Comment by nurmi** [comment]
Hi @agentreno - fortunately, this is a known issue (related to the way that tar interacts with certain docker storage drivers) and there is a pretty simple workaround!  For some background context, see this issue https://github.com/anchore/anchore-engine/issues/15

In a nutshell, the simplest solution if you're experiencing this issue is to mount a volume into your anchore-engine container and configure your engine to use that location as its workspace - the following snippets show an example of this, assuming the default '~/aevolume` layout that we document for quick-start with docker-compose:

```
# ls -lad workspace
drwxr-xr-x 2 root root 6 Jun 29 09:51 workspace
# cat docker-compose.yaml 
version: '2'
services:
  anchore-engine:
    image: docker.io/anchore/anchore-engine:v0.2.4
...
...
...
    volumes:
     - ${PWD}/config:/config/:z
     - ${PWD}/workspace:/workspace/:z
...
...
...
# cat config/config.yaml
# Anchore Service Configuration File
...
...
tmp_dir: /workspace
...
...
```

With the above configuration, you're making the ~/aevolume/workspace directory from your host available as /workspace inside the anchore-engine container environment.  As long as the ~/aevolume/workspace directory is a filesystem that is appropriate, then this avoids the overlay2 docker/kernel/tar interaction bug references in the above ticket.

If you're using OSX, then we'd recommend that you use a docker volume (instead of an external directory volume) instead, since OSXfs has other incompatibilities with untarring linux files (like dev entries/etc).  That would look something like this (where in this example I've setting up a relatively small workspace volume of 4GB, for a real system we recommend a workspace volume of at least 3x the size of the largest image you plan to analyze):

```
# docker volume create -o 'o=size=4000m' -o device=tmpfs -o type=tmpfs anchore-workspace
anchore-workspace

# cat docker-compose.yaml
cat docker-compose.yaml
version: '2'

volumes:
  anchore-workspace:
    external: true
...
...
...
services:
  anchore-engine:
...
...
    volumes:
     - ./config:/config/:z
     - anchore-workspace:/workspace:z
...
...
```
                                                                                     
Hope this helps!  Let us know how it goes.
